### ISSUE TITLE
file operations fail on shared/synced folders that do not implement correct filesystem semantics

### ISSUE THREAD

**Issue by dopry** [ansible/ansible#9526]
##### Issue Type:

“Bug Report”, 
##### Ansible Version:

1.7.2
##### Environment:

Ubuntu 14.04.1 VM on Virtual Box 4.3.14  on Windows 8.1 
I know the issue is likely specific to vboxfs 
##### Summary:

The copy modules fails on virtual box shared folders. specifically the os.rename() fails.  I tried replacing the os.rename with shutils.copy2 and it worked fine.  

I notice there is a lot of working being done in atomic_move. There is a fallback strategy that seems to attempt to copy the source file to a temp file in the destination directory, and then rename the temp file. Why not just do the copy straight to the destination and let cleanup() handle the stuff in the temp folder?

I tested a few scenarios if I try to copy to some place besides the shared folder, the module works. So the source doesn't appear to be what is blocking the rename, but it's the destination. I tried hard coding an alternate destination at the os.rename, in case a previous operation was taking a lock, but still kept receiving error 26.

When I try opening up the repl, I get a slightly different error, but an error none the same..

> > > import os
> > > os.rename('test.txt', '/vagrant/test.txt')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > OSError: [Errno 18] Invalid cross-device link

It looks like os.rename doesn't work across partitions, and this is the root of the problem. (maybe this is why it tries to copy to the save folder as the destination, then renames).

https://mail.python.org/pipermail/python-list/2005-February/342893.html
https://bugs.launchpad.net/python-keystoneclient/+bug/1265190
##### Steps To Reproduce:

install virtualbox. 

put all the files from  https://gist.github.com/dopry/4bc4f2d852b8055a7b68 in a folder.

vagrant up 
vagrant ssh 

from inside the vm..

echo "test" > test.txt
ansible web -i /vagrant/ansible/inventory/vagrant/hosts.py -m copy -a "src=test.txt dest=/vagrant/test.txt"
##### Expected Results:

test.txt is copied to  /vagrant.
##### Actual Results:

vagrant.dev | FAILED >> {
    "failed": true,
    "md5sum": "bbfa1f311a5828452b953d1335cbf027",
    "msg": "could not cleanup /vagrant/.ansible_tmpE8ytJhtest.txt: [Errno 26] Text file busy: '/vagrant/.ansible_tmpE8ytJhtest.txt'{\"msg\": \"Could not replace file: /home/vagrant/.ansible/tmp/ansible-tmp-1415586483.17-87111780037684/source to /vagrant/test.txt: [Errno 26] Text file busy\", \"failed\": true}\r\n",
    "parsed": false
}

**Comment by dopry** [comment]
If someone else is experiencing this problem I worked around it by copying to the remote home then moving with command.  (the ansible tmp dir is in the remote home, I assume it will generally be the same partition)
- copy:   src="test.txt" dest= "test.txt"
- command: mv test.txt /vagrant/test.txt"

**Comment by mpdehaan** [comment]
There is no win_copy module at this time, so this is why the module cannot be used on Windows.

It seems we should instate a check to make sure modules implemented in Python don't get attempted to be executed in this way.

**Comment by cchurch** [comment]
This has nothing to do with win_copy or connecting to a Windows host; it appears to be an issue when copying a file to a Linux host, where the destination is on a virtualbox shared folder.

**Comment by dopry** [comment]
Ansible is running in and connecting to a linux VM. The VM is running on
windows.  It's trying to copy a file from the VM's root filesystem to the
/vagrant folder. the /vagrant folder has a vboxfs filesystem mounted to it.
os.rename seems to fail when copying from the root to the vboxsf partition.
It also fails when renaming a file on the vboxsf partition. If you want I
can setup a repo just to demonstrate the bug for you. I haven't confirmed
if this happens if linux or mac are hosting the VM.

On Mon, Nov 10, 2014 at 3:55 PM, Michael DeHaan notifications@github.com
wrote:

> There is no win_copy module at this time, so this is why the module cannot
> be used on Windows.
> 
> It seems we should instate a check to make sure modules implemented in
> Python don't get attempted to be executed in this way.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/9526#issuecomment-62453258.

## 

Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101

**Comment by RowboTony** [comment]
Thank you @dopry for this information! This problem has been driving me mad for about the past three hours. Win7 x64, VirtualBox 4.3.20, Linux guest Ubuntu 14.04, synced_folder, Ansible running within the guest, it can't copy one particular file from Linux to vboxfs.

```
==> default: <default> PUT /tmp/tmpGKnnSx TO /root/.ansible/tmp/ansible-tmp-1417932523.39-220512482662826/source ==> default: <default> PUT /tmp/tmp4eB2Z2 TO /root/.ansible/tmp/ansible-tmp-1417932523.39-220512482662826/copy
==> default: <default> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1417932523.39-220512482662826/copy; rm -rf /root/.ansible/tmp/ansible-tmp-1417932523.39-220512482662826/ >/dev/null 2>&1']
==> default: failed: [default] => {"failed": true}
==> default: msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1417932523.39-220512482662826/source to /var/www/sites/local.example.com/settings.php: [Errno 26] Text file busy
==> default:
==> default: FATAL: all hosts have already failed -- aborting
111
```

**Comment by dopry** [comment]
Fetch and template are not equivalent. Fetch does not interpolate variables
and expressions.

**Comment by defeated** [comment]
having a similar problem copying file from local client to remote server, which is using a network attached storage device - using **ansible 1.8.2** -

``` yml
    - name: upload ping file
      copy: src="templates/ping.html" dest="/mnt/files"
```

fails with -

> Could not replace file: /home/me/.ansible/tmp/ansible-tmp-1420234876.35-71225400803213/source to /mnt/files/ping.html: [Errno 95] Operation not supported

but if I do a `copy` to remote server and then manually `move` it to the network storage, it works fine -

``` yml
    - name: upload ping file
      copy: src="templates/ping.html" dest="/tmp"
    - name: move ping file
      command: mv /tmp/ping.html /mnt/files
```

(The downside is more complexity in the playbook to make this idempotent)

**Comment by saada** [comment]
I'm having the exact same issue but using the `template` module. Any ideas for at least a workaround using the `template` module?

**Comment by gbuckerfieldcruk** [comment]
Having a very similar issue with 1.8.2 on a Ubuntu 14.04.1 virtual machine running in Virtualbox, while using the `template` module.

The destination path is an NFS share exposed in the VM via Vagrant. The action actually looks like it succeeds (the file is created with the correct variables populated) but the task reports that it's failing.

In the playbook:

```
- name: create local.settings.php
  template: src=local.settings.php.j2  dest=/var/www/site/docroot/sites/default/local.settings.php mode=0644 backup=yes
  sudo: yes
```

The output:

```
TASK: [post_install | create local.settings.php] ****************** 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1423143555.31-218436313464603/copy", line 1824, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1423143555.31-218436313464603/copy", line 238, in main
    module.atomic_move(src, dest)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1423143555.31-218436313464603/copy", line 1624, in atomic_move
    os.chown(dest, os.getuid(), os.getgid())
OSError: [Errno 1] Operation not permitted: '/var/www/site/docroot/sites/default/local.settings.php'
Exception OSError: (2, 'No such file or directory', '/var/www/site/docroot/sites/default/.ansible_tmpp1DIX7local.settings.php') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7fa03ecbc300>> ignored

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
does anyone have this issue outside of vagrant synced folders? is is only with the virtualbox backend? and only when physical host is windows?

Most of the file plugins (non win_) use the atomic_move function to ensure consistency and atomicity of its results. This function  requires a posix filesystem (which is an ansible requirement), NTFS is not compliant and can cause issues.

**Comment by defeated** [comment]
@bcoca yes, I do, I'll give some additional context for my comment above -https://github.com/ansible/ansible/issues/9526#issuecomment-68566699 -

That was trying to copy a file from local OS X machine to remote Ubuntu 14 guest running on VMWare ESXi host. (I don't have specific details about the storage device mounted under `/mnt/files` but could retrieve it, if that would help?)

**Comment by bcoca** [comment]
yes, as I run a full linux stack with virtualbox and am not able to reproduce this problem

**Comment by gbuckerfieldcruk** [comment]
Just to add, I was seeing the problem with an Ubuntu host (14.10), virtualbox and an Ubuntu VM (14.04). The vm is provisioned through Vagrant and the destination path is a Vagrant NFS share.

The workaround I had to use was an Ansible shell command to touch the file just before trying to overwrite it with the template module.

```
- name: create empty local.settings.php if required
  shell: cd /var/www/site/docroot/sites/default; touch local.settings.php
  when: not local_settings_php.stat.exists

- name: create local.settings.php
  template: src=local.settings.php.j2  dest=/var/www/site/docroot/sites/default/local.settings.php mode=0644 backup=yes
```

**Comment by dopry** [comment]
I believe happens when copying across any mount point on a POSIX system.
This is not limited to vagrant or virtual box.

**Comment by bcoca** [comment]
@dorpy, the code accounts for that, if a direct rename (which doesn't work across filesystems) fails, it copies a temporary file to the target directory and then does a rename there.

**Comment by dopry** [comment]
Yeah, but that process fails. I believe I documented that in earlier
comments. It's a bit hard to check my notes now.  I'm on holiday in the
Dominican Republic. I'll be stateside next week and can follow up then if
the examples fail.

**Comment by saada** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=656225

Same issue with glib.

**Comment by tomgidden** [comment]
I'm seeing a similar problem when using the `authorized_key:` module on a `vboxsf`-mounted filesystem: `Could not replace file: /www/default/tmph3jXcn to /www/default/keys: [Errno 26] Text file busy`

I got around the `copy:` problem above by using the `synchronize:` module to sync the `copy:`'ed tree from `/tmp/www/` to `/www/` conditionally `when: ansible_devices.sda is defined and ansible_devices.sda.model == 'VBOX HARDDISK'`

However, the `authorized_keys:` issue might be harder to solve, as there's no equivalent operation... it might have to be a `lineinfile:` instead.

To clarify, that's running Ansible 1.8.4 on Ubuntu Linux (trusty32) inside a Vagrant VM running on Windows 7.  `/www` is a mount of type `vboxsf`. While it is running inside a Windows-hosted VM, Ansible's running in the Linux VM, talking to itself using an `ansible_connection=local` host.  This is to get around the problem of not having Ansible for Windows to provision a Vagrant VM directly.

**Comment by zsoldosp** [comment]
a gist reproducing the problem: https://gist.github.com/zsoldosp/777a6fd7d242c2c1dabd/ 

(**edit** after @dopry's request for more info)
Host: Win7 x64, Vagrant 1.7.2, VirtualBox 4.3.24 r98716
Guest: It's in the Vagrantfile, ubuntu/trusty64 (14.04), ansible 1.8.2 

Download the gist, and run `vagrant up` (or `vagrant provision` when running multiple times). Currently it gives the ErrNo 26: text file is busy... error

**Comment by dopry** [comment]
@zsoldosp: what host os/guest os combination are you using?

**Comment by saada** [comment]
For me it's on Windows 7 host, Ubuntu 1404 guest

**Comment by jensenbox** [comment]
I seem to be fighting ansible every time I turn around. Running on Windows 7 to a Vagrant with shared folders just seems to be broken on several layers - the 'every file is executable' problem and now writing out simple text files from a template... will it end after this?

**Comment by bcoca** [comment]
@jensenbox ansible was designed with posix systems in mind, if you use non posix systems it is predictable you'll hit some issues. That said, we are working on making it easier for people to do so.

**Comment by altmind** [comment]
i hope that posix-oriented-ness is not carved in stone and that some day ansible team will reconsider supporting windows :)

**Comment by bcoca** [comment]
we are adding windows as a target, there are no plans to support windows as a controller/master

**Comment by jensenbox** [comment]
@bcoca I think I have at least narrowed down the problem to something that is mildly fixable...

So it is in fact a 'cross partition' issue. The template task is creating a temp file of the result in the current users home directory and then doing an atomic os.rename.

Because /vagrant is technically on a different filesystem it is failing - but with what I suspect to be an invalid error code. 

```
msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1427476564.34-155580542794406/source to /vagrant/src/officepools/local_settings.py: [Errno 26] Text file busy
```

There are two points in the following code that could be returning the same error here: https://github.com/ansible/ansible/blob/60f972dfe4bc58180c666f820ef2d602acf917e4/v2/ansible/module_utils/basic.py#L1336

I even went as far to have the templated file store its result on the current posix filesystem then copy the file to the non-posix directory and the copy function fails as well. Pretty much the same error:

```
msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1427477026.96-38878336250870/source to /vagrant/src/officepools/local_settings.py: [Errno 26] Text file busy
```

Turns out that they are both using the exact same module base (nice and DRY)

So I tried the 'command' to have the os move it and all was good.

This:

```
- template: src=local_settings.py.jinja2 dest="{{ directories.src }}/{{ names.codename }}/local_settings.py"
```

becomes this:

```
- template: src=local_settings.py.jinja2 dest=/root/local_settings.py.temp
- command: mv /root/local_settings.py.temp {{ directories.src }}/{{ names.codename }}/local_settings.py
```

and all is good. 

Seems like Ansible could be modified pretty easily to fix at least this corner case.

**Comment by nmunson** [comment]
@jensenbox thanks for the tip on using command, that's worked for me in bumping into this as well.  Any ideas on how to make this idempotent?

**Comment by bcoca** [comment]
@jensenbox so if we incorporate error #26 'file too busy' and attempt to copy it non-atomically it should solve this issue? I would like to narrow it down to non-posix file systems as that is a valid error, though rare in the posix case.

**Comment by bcoca** [comment]
let me know if the above hack mitigates the issue.

**Comment by bcoca** [comment]
So it seems this has reared it's head for other tools on vagrant, which then pushes the issue to virtualbox/windows.
https://github.com/mitchellh/vagrant/issues/1446
https://github.com/mitchellh/vagrant/issues/2282

What I get from this is DO NOT USE SHARED/SYNCED folders in production if you care about your files. Strange stuff can happen.

**Comment by dopry** [comment]
In this specific case, there are provable testable issue where python's os.rename fails to rename a file, where the shell's mv command can.  

vboxsf implements enough of the posix filesystem interface to support these items.  There are known shortcomings of vboxsf. It does not support links. Permissions are statically defined for the mount point and immutable. There is also a class of sync/flush related issues where the host and guest os do not sync files in a timely manner and do not signal each other's cache of changes so you can edit the files in one os and not see the change in the other. 

There are work arounds for all of the shortcomings of vboxsf. Don't use links, Don't depend on permissions, only edit files on the host or client not both, if editing on the host disable aggressive client side caches like sendfile in web servers and things depending on inotify. 

Also vboxsf, which is flawed and maintained by Oracle and the virtualbox team, isn't the only options for virtualbox shared files. There is also NFS and SMB. I even did some of the work to add symlink / NTFS link support to winnfsd to work around these issues. 

Your assertion  'DO NOT USE SHARED/SYNCED folders' should be 'USE vboxsf SHARED/SYNCED folders with CAUTION'.

In this case it's the vboxsf or python team's problem.  I'm going to close it here since it's apparent that there is no intent from the Ansible team to work around this issue and I'd rather see it move to the upstream maintainer's queue's before more FUD clouds the issue.

**Comment by bcoca** [comment]
@dopry , I just asked above for testing on a PR that works around it, so WE ARE working on the issue, this is why I'm reopening this ticket until i get confirmation if it mitigates it or not (aside from my local tests). 

I admit the 'DO NOT USE' might sound a bit harsh, but I also say that about most network/fuse filesystems as they do not always do what people expect and fail in "fun and interesting ways" (including NFS). They all have issues with POSIX semantics, multiple source writes and translating networking issues to file related errors.

This is not a python os.rename issue its the system call 'rename' which is called by it, We use os.rename to attempt to preserve atomicity in the change, which keeps file integrity in the view of any other apps that can access it at the same time. We fall back to "copy and unlink", as most of the mv implementations do, but only on specific errors (which some mv do, some will try with any error), normally that you are crossing a partition boundary (EXDEV). We try to avoid by putting the tmp file in the same dir which should guarantee the samet parition. In this case we are getting a seemingly unrelated error and my patch addresses by adding the errno 26 to this list, we don't do it on ANY error as there are cases in which it is legitimate to fail (permissions for example).

When I linked the upstream Vagrant tickets I did not mean to 'pass the buck', but to show that this is a deeper issue for which it will be hard for Ansible to provide a good solution. Each hop upstream shows that the problem comes from things that were never meant to work this way, cobbled together to make it seem it does, and generally is good enough. But then we run into the exceptions, get really mixed signals from the errors and end up creating 'hackish' solutions like my PR to compensate.

**Comment by jensenbox** [comment]
I think an easy solution (hack) would be to allow the template task to have the temp file location specified. In this case I would point it to a temp location on the same file system and it should work nicely. There are a few areas in Ansible that make use of the same function,  probably not a terrible idea to allow that param in the respective tasks as well - OR set up some sort of variable that Ansible looks at in its processing - perhaps a host or group var?

**Comment by bcoca** [comment]
@jensenbox atomic_move already makes a tmp copy in the same directory as the target, this is why os.rename works on POSIX filesystems, the problem here is that it fails with errno26 'text file too busy'.

**Comment by javiplx** [comment]
Although #10914 solves the issue, the [uid verification on line 1387](https://github.com/ansible/ansible/commit/9ec7eb30d28d54d49867d6c8768214766988c2d7#diff-90085fdcec6ed8b273ba885eaee60328R1387) does reproduce the captured error if the task is performed as root user.

**Comment by javiplx** [comment]
After working a bit more with this, I've realized that the problem was not on line 1387 but [on line 1403](https://github.com/ansible/ansible/commit/9ec7eb30d28d54d49867d6c8768214766988c2d7#diff-90085fdcec6ed8b273ba885eaee60328R1403), where the same `os.rename` that caused the captured error is attempted again.

**Comment by sergeytsivin** [comment]
Yes, the problem is not fixed. As pointed out by @javiplx the second `os.rename` [on line 1403](https://github.com/ansible/ansible/commit/9ec7eb30d28d54d49867d6c8768214766988c2d7#diff-90085fdcec6ed8b273ba885eaee60328R1403) fails. 

First os.rename fails because of errno 18 (cross device) -- this is not vagrant shared folder specific, but the second one returns 26 (text file busy) because of a [bug 9203](https://www.virtualbox.org/ticket/9203) in Virtualbox's vboxsf file system: can't rename an open file on vboxsf on Windows host. And temporary file is open when attempting to rename.

A work-around for this issue is to tell ansible to create temprary folder on the same file system as the destination files, i.e. /vagrant. This can be accomplished in the `ansible.cfg` like this:

```
  [defaults]
  remote_tmp     = /vagrant/ansible_tmp
```

This way the first os.rename doesn't fail and all works well.

**Comment by dopry** [comment]
@sergeytsivin @javiplx, I was able to solve the problem. I stopped using ansible/vagrant, and moved to docker/compose.  I haven't looked back. It's saving my team tons of time waiting on provisioning and fighting with errors. Its easy to script remote commands with docker run. 

Docker the company and the surrounding community is truly supportive of windows users and really works to solve the problems rather than being dismissive. I feel like my time with ansible was wasted.

**Comment by chadrobertson75** [comment]
This problem is extremely frustrating. I have gone from knowing it would happen in Windows hosts to now seeing it happen in Ubuntu hosts as well. Seems to be the only way to deal with it in a virtualbox environment is to double down on copying files which feels dirty.

**Comment by thiagotalma** [comment]
@bcoca Please, reopen this issue and solve this...... :disappointed:

**Comment by sergeytsivin** [comment]
While @bcoca's PR doesn't mitigate the problem, there's a workaround that my team successfully uses: just set the `remote_tmp` to be somewhere on the `/vagrant` folder.

**Comment by chriscollinsboxuk** [comment]
I'm also experiencing this issue - the workaround of setting `remote_tmp` does not work for me. In some cases I've been able to replace one copy with two, but other issues are more difficult to fix without making the playbook less readable (e.g. I'm experiencing the issue when using `lineinfile`).

**Comment by sergeytsivin** [comment]
Just to clarify the case where `remote_tmp` workaround helped:

I am running vagrant with virtualbox 4.3 on Windows 7 host with Ubuntu 14.04 as guest. Ansible 2.0.1.0 is installed on the guest and I am running the `ansible-playbook` command from within the guest. The target host is described in inventory as having ansible_connection=local 

Any `template` command with destination file on `/vagrant` folder had been failing with "Could not replace file: ...[Errno 26] Text file busy" error until I changed the `remote_tmp` setting. 

I have created `/home/vagrant/.ansible.cfg` file with the following settings:

```
[defaults]
remote_tmp = /vagrant/ansible/tmp
log_path = /vagrant/ansible/ansible.log
```

Once this has been setup the error is gone.

I use `bootstrap.sh` script to install ansible and create the config:

```
#!/bin/bash

apt-get remove ansible
apt-get install -y python-pip && sudo pip install ansible

cat > /home/vagrant/.ansible.cfg <<EOF
[defaults]
remote_tmp = /vagrant/ansible/tmp
log_path = /vagrant/ansible/ansible.log
EOF
```

**Comment by synweap15** [comment]
@sergeytsivin I've used similar bootstrap script, but without the .ansible.cfg part  - now it works correctly with the defaults set and `remote_tmp` present. Thanks for sharing!

**Comment by externl** [comment]
Still not working for me. Even with `remote_tmp` set to something inside the shared directory in the guest's `~/.ansible.cfg`.

**Comment by mb222** [comment]
about copying the file into Synced folder using Vagrant and Ansible. I was getting the same error:

vagrant.dev | FAILED >> {
"failed": true,
"md5sum": "bbfa1f311a5828452b953d1335cbf027",
"msg": "could not cleanup /vagrant/.ansible_tmpE8ytJhtest.txt: [Errno 26] Text file busy: '/vagrant/.ansible_tmpE8ytJhtest.txt'{\"msg\": \"Could not replace file: /home/vagrant/.ansible/tmp/ansible-tmp-1415586483.17-87111780037684/source to /vagrant/test.txt: [Errno 26] Text file busy\", \"failed\": true}\r\n",
"parsed": false
`}`

To fix this I created the file in the syncged folder first, then used the Ansible's 'command' module and used the Unix 'cp' command.

The example will look:
- name: create test.txt file
  file: path={{ sync_dir_location }}/test.txt state=touch owner=root group=root mode=0775
  - name: Copy the test.txt file to shared folder location
    command: cp test.txt {{ sync_dir_location  }} chdir = {{ test.txt_current_location }}

**Comment by damienwebdev** [comment]
I'm still seeing this when trying to move/copy a template into a shared_folder on an Windows 10 host with an Ubuntu 16.04 guest.

**Comment by brycethornton** [comment]
The solution to "touch" the file first before copying worked for me. See @mb222's comment above.

**Comment by lukasojd** [comment]
+1 in version 2.2.0.0 ansible make
