### ISSUE TITLE
Allow inventory files to be defined with yam instead of ini

### ISSUE THREAD

**Issue by kidbrax** [ansible/ansible#9532]
It seems counterintuitive to define inventory with .ini files when the rest of configuration is defined in yam format.  It would be easier and more consistent if you could use yam for the inventory files as well.

**Comment by mpdehaan** [comment]
Inventory is a graph, YAML's a tree, we had this in the past and explicitly removed this.

Feel free to join ansible-project list if you'd like to discuss further, but I'm going to go ahead and close this ticket as this behavior will not be changing.

(See also dynamic inventory sources for other options)
