### ISSUE TITLE
shell/command modules: Extraneous single quote being prepended to command

### ISSUE THREAD

**Issue by manicminer** [ansible/ansible#9538]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ubuntu@ip-xx-xxx-xx-xxx:~/tom/ansible$ ansible --version
ansible 1.7.2
```

Also occurs with latest 1.8 HEAD running from a fresh git clone sourced with `. hacking/env-setup`

```
ubuntu@ip-xx-xxx-xx-xxx:~/tom/ansible$ ansible --version
ansible 1.8 (devel fa953e162e) last updated 2014/11/11 14:40:22 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 6317d3a988) last updated 2014/11/11 14:40:27 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 5a514ccdda) last updated 2014/11/11 14:40:31 (GMT +000)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/11 14:40:36 (GMT +000)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/11 14:40:42 (GMT +000)
  configured module search path = /usr/share/ansible
```
##### Environment:

Ubuntu 14.04.1 amd64 on EC2
##### Summary:

I am using the shell module to install RVM using a globally installed rvm executable. No matter whether I use the shell or the command module, an extraneous quote is being inserted at the beginning of my command and causing either module to fail.
##### Steps To Reproduce:

Please see https://gist.github.com/tombamford/2ceff646e72f2885fa34 for example playbook and inventory file to reproduce the issue. Gist also includes verbose output from running `ansible-playbook`.
##### Expected Results:

The command to be run evaluates to:

```
/usr/local/rvm/bin/rvm install 2.0.0-p353
```

This command should be run on the remote node.
##### Actual Results:

The command appears to be evaluated as:

```
' /usr/local/rvm/bin/rvm install 2.0.0-p353
```

(note the phantom single quote at the start of the command)

This causes the shell module to fail with the following error:

```
failed: [acceptance] => {"changed": true, "cmd": "' /usr/local/rvm/bin/rvm install 2.0.0-p353", "delta": "0:00:00.007263", "end": "2014-11-11 14:41:43.830322", "rc": 1, "start": "2
014-11-11 14:41:43.823059", "warnings": []}
stderr: /bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file
```

Please see the gist at https://gist.github.com/tombamford/2ceff646e72f2885fa34 for full output.

**Comment by manicminer** [comment]
I narrowed down a workaround (and possible clue as to the cause).

Removing the 'creates:' line makes the issue go away, as does changing it to 'equals notation' such as:

```
- name: Install Ruby
  shell: /usr/local/rvm/bin/rvm install {{ ruby_version.content | b64decode }}
         creates=/usr/local/rvm/rubies/ruby-{{ ruby_version.content | b64decode }}
  args:
    executable: /bin/bash
```

**Comment by jimi-c** [comment]
Hi, this situation is no longer present in the devel branch (which will be ansible 2.0)

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
