### ISSUE TITLE
Enforce that the setup module creates only alpha-numeric + underscore fact names

### ISSUE THREAD

**Issue by bladypirat** [ansible/ansible#954]
I've found problem while trying to access ip address reported by setup module:
"ansible_br-test": {
"device": "br-test", 
"ipv4": {
    "address": "10.13.0.23", 
    "netmask": "255.255.255.0", 
    "network": "10.13.0.0"
},
Tried:
${ansible_br-test.ipv4.address}
{{ ansible_br-test["ipv4"]["address"]}} 

Seems like ansible uses "-" as separation  mark
fatal: [hostname] => {'msg': "'test' is undefined", 'failed': True}
br-test is custom network bridge name.

**Comment by mpdehaan** [comment]
Good catch.

We should probably replace all "-"'s with underscores before returning them.

**Comment by mpdehaan** [comment]
fixed per above
