### ISSUE TITLE
Ansible seems to freeze running shell task

### ISSUE THREAD

**Issue by joriss82** [ansible/ansible#9550]
I was rolling out a playbook. A certain shell task contained an unzip (true, this could be done with the unarchive module, but it was not unfortunately).
The unzip on the target machine seemed complete (dir size was correct and all files were present) but Ansible did not continue to the next task, nor did it throw an error.

I am using Ansible 1.7.2.

Logging info was not very helpful, it just showed what I saw in the output of ansible when running, so no errors or anything.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
