### ISSUE TITLE
ownership of files after unarchive

### ISSUE THREAD

**Issue by fauzigo** [ansible/ansible#9553]
Hi,

is there any way to set the ownership of everything after unarchive?

I'm actually doing the following:

```
- name: Extrat the sources
  unarchive: src={{ home_dir }}/file-{{ file_version }}.tar.gz dest={{ home_dir }} copy=no group={{ file_user_group }} owner={{ file_user }}
```

This user and group is not working  so I added after that task

```
- name: Set the right ownership
  command: /usr/bin/chown -R {{ file_user }}.{{ file_user_group }} {{ home_dir }}/file-{{ stash_version }}
```

I know this is OK, but I was wondering if there where any other easier way to do it since sometimes what's extracted do not comes with a directory with the same name as the tarball, or even worst the extraction occurs inside a directory full of other archives.

Thanks in advance.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
