### ISSUE TITLE
"ImportError: No module named ansible" after update

### ISSUE THREAD

**Issue by HenryTheHamster** [ansible/ansible#9558]
After pulling the latest (e79acf3f88) changes to Ansible, a basic playbook is failing with...

```
SUDO-SUCCESS-rbkflosiapqhpzjqxrhrgckuqnazbbqs
Traceback (most recent call last):
  File "/home/wins/.ansible/tmp/ansible-tmp-1415946160.19-172660761664895/setup", line 8, in <module>
    from ansible import __version__, __author__
ImportError: No module named ansible
```

...using the playbook...

```

---
- hosts: all
  sudo: yes
  tasks:
  - name: Testing
    debug: msg="I'm selling these fine leather jackets..."
```

... and running using...

```
ansible-playbook test.yml --ask-pass
```

Python on the target box is 2.6.6.
Control machine is running OSX 10.8.5

This is the first pull I've done since the git submodules were introduced, and this seems like it could be related to them in some way? Keeping the temp file shows the setup.py file trying to import from ansible, but it was my understanding that I shouldn't require that on the target machines.

**Comment by mpdehaan** [comment]
I'm curious how you are getting this output, but we're using the development branch fine over here.  

Can you stop by https://groups.google.com/forum/#!forum/ansible-project (i.e. the mailing list) for help 
debugging this one?  We can continue there.

It seems like a simple install / running-from-source issue.

Thanks!
