### ISSUE TITLE
webserver[0:1]  can't matche the hosts via ansible 1.8

### ISSUE THREAD

**Issue by geekwolf** [ansible/ansible#9569]
OS:Ubuntu 14.04.1 LTS <br>
 Is a bug?
![ansible](https://cloud.githubusercontent.com/assets/3125615/5064625/a3570086-6e48-11e4-8990-5b6e0695edd2.png)

**Comment by geekwolf** [comment]
I think that the official document writing is wrong, should use the "-" instead of the ":" <br>
example:<br>
"ansible webserver[0-1]  -m ping"  not the "ansible webserver[0:1] -m ping"

**Comment by bcoca** [comment]
this will work as a list

```
ansible 'webserver[0,1]' -m ping
```

it is not a range operator, so : and - really have no meaning in it.

not to be confused with ranges defined in inventory files.

**Comment by mpdehaan** [comment]
I wasn't aware the list syntax would work, actually.

Given this isn't included in the docs as a feature, I think, I believe we can close this.

If you have further questions, please stop by ansible-project and we'd be happy to discuss.
