### ISSUE TITLE
dependencies in requirements.yml do not use path

### ISSUE THREAD

**Issue by michaelfavia** [ansible/ansible#9572]
_Description_: If you have specified a path for your required dependency it should be preserved for all requirements id assume.

Example requirements.yml:

```
# drush from galaxy installing to a relative path in this project
- src: geerlingguy.drush
  path: roles/
```

_Desired operation_: Should download the dependency (geerlingguy.php) to the reltive path "roles" as well.

_Actual Result_: Tries and fails to download it to /etc/ansible/roles/ which i assume is the "role_path" on this machine.

_Workaround_: Any wayward souls looking for a short term fix can find one by using a local ansible.cfg instead:

```
[defaults]
roles_path = roles/
```

_Version_: Ansible master branch as of issue date.

**Comment by jctanner** [comment]
We don't have "path" listed as an option in the requirements.yml documentation, and I suspect that this scenario might be why:
http://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file

It could be hairy trying to juggle the install path if each role in the requirements defines a different path. I think using ansible.cfg or the --roles-path option is a better approach.
