### ISSUE TITLE
Windows install of Ansible using pip fails because of pwd module (not a dupe of #7049)

### ISSUE THREAD

**Issue by mrichman** [ansible/ansible#9576]
I have the same problem as Issue #7049, except I'm not using cygwin. I just installed the official Python 2.7 installer, then ran  `python get-pip.py` to install `pip`. When running `pip install ansible`, I get the above error "ImportError: No module named pwd".

**Comment by sivel** [comment]
Windows is not a supported operating system for an ansible control machine  Ansible requires a nix like operating system for installation.  See http://docs.ansible.com/intro_installation.html#control-machine-requirements

**Comment by cchurch** [comment]
What @sivel said.  Also mentioned here: http://docs.ansible.com/intro_windows.html#reminder-you-must-have-a-linux-control-machine
