### ISSUE TITLE
duplicate role execution with role denpendencies

### ISSUE THREAD

**Issue by MorphBonehunter** [ansible/ansible#9578]
**Issue Type:**
Bug Report

**Ansible Version:**
ansible 1.7.2 (1.7.2+dfsg-2~bpo70+1)

**Environment:**
Debian 7.7

**Summary:**
Today i try to split our grown ansible roles in more simple roles.
After do some work i realize that after rewrite and set some dependencies in our roles, some roles got executed multiple times.
So i google a bit and found an bug report (https://github.com/ansible/ansible/issues/5971) which descibe the same behavior.
The bug gets closed because of not reproducable and no further information.

So i recreate the simple test in comment nr. 4 and BAM...no duplicate running!
After some testing i figured out the only difference to our plays.
The duplicate run is triggered if you add some tags to the play.

As sugested in https://groups.google.com/d/msg/ansible-project/3Tc6MUZ1dFI/JHFNplVccxcJ i've open this bug report.

**Steps To Reproduce:**
run without duplicates:

```
# test.yml

---
- name: dependency test
  gather_facts: false
  hosts: localhost
  connection: local

  roles:
    - { role: base }
    - { role: feature }

# roles/base/meta/main.yml

---

# roles/base/tasks/main.yml

---
- name: in base
  debug: msg="here we are in base"

# roles/feature/meta/main.yml

---
dependencies:
  - { role: base }

# roles/feature/tasks/main.yml

---
- name: in feature
  debug: msg="here we are in feature"

PLAY [dependency test] ********************************************************

TASK: [base | in base] ********************************************************
ok: [localhost] => {
    "msg": "here we are in base"
}

TASK: [feature | in feature] **************************************************
ok: [localhost] => {
    "msg": "here we are in feature"
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

run with duplicates:

```
# test.yml

---
- name: dependency test
  gather_facts: false
  hosts: localhost
  connection: local

  roles:
    - { role: base, tags: base }
    - { role: feature, tags: feature }

# roles/base/meta/main.yml

---

# roles/base/tasks/main.yml

---
- name: in base
  debug: msg="here we are in base"

# roles/feature/meta/main.yml

---
dependencies:
  - { role: base }

# roles/feature/tasks/main.yml

---
- name: in feature
  debug: msg="here we are in feature"

PLAY [dependency test] ********************************************************

TASK: [base | in base] ********************************************************
ok: [localhost] => {
    "msg": "here we are in base"
}

TASK: [base | in base] ********************************************************
ok: [localhost] => {
    "msg": "here we are in base"
}

TASK: [feature | in feature] **************************************************
ok: [localhost] => {
    "msg": "here we are in feature"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Expected Results:**
If the playbook is run, and the roles are tagged the dependencys should run only once.

**Actual Results:**
If the playbook is run, and the roles are tagged the dependencys run multiple times.

**Comment by kovacsbalu** [comment]
same here with version: 1.9.1
running with "--list-tasks"

```
playbook: playbook.yml

  play #1 (dependency test):    TAGS: []
    in base TAGS: [base]
    in base TAGS: [feature]
    in feature  TAGS: [feature]
```

**Comment by bcoca** [comment]
this is expected, the 'no duplicates' is not just on role name but on the role 'signature' so by passing different tags you make them 'differnt roles'.

**Comment by kovacsbalu** [comment]
ok, thanks!
