### ISSUE TITLE
Feature request: Ability to skip includes

### ISSUE THREAD

**Issue by jnojr** [ansible/ansible#9581]
Currently, if I do something like:

```
- include: some_other.ml
  when: some_condition == some_result
```

The included playbook is parsed and every step in it is skipped if the conditional is not met.  This can generate a lot of extraneous output to no useful end, since nothing is going to be done.  Can we get unusable to be able to simply ignore the include?  Even if that would require a different module, like cond_include?

**Comment by bcoca** [comment]
This is not something that can be done without major restructuring of how ansible works. 

The good news is that we are already doing that (look at v2 work in the repo).

**Comment by bandesz** [comment]
@bcoca Will the when work for playbook includes too in v2?

**Comment by bcoca** [comment]
@bandesz I would not expect it to

**Comment by bcoca** [comment]
closing as this is currently working in devel
