### ISSUE TITLE
NameError: global name 'group' is not defined

### ISSUE THREAD

**Issue by HeisenbergTT** [ansible/ansible#9604]
Trying to run ec2_group to create security groups in AWS:
- name: 'Create Magneto security group: {{ magneto_group }}'
  local_action:
    module: ec2_group
    name: "{{ magneto_group }}"
    description: "{{ magneto_description }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp # ssh
        from_port: 22
        to_port: 22
        group_name: "{{ jumpbox_group }}"
        group_desc: "{{ jumpbox_description }}"
      - proto: tcp # http
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp # http
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        group_name: tt-magneto-group
        group_desc: "a security group for magneto nodes"
      - proto: all
        cidr_ip: 0.0.0.0/0

This produces this error:
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1416814033.8-57159820801170/ec2_group", line 1770, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1416814033.8-57159820801170/ec2_group", line 292, in main
    group_id, ip, target_group_created = get_target_from_rule(rule, name, groups)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1416814033.8-57159820801170/ec2_group", line 139, in get_target_from_rule
    group_id = group.id
NameError: global name 'group' is not defined

The security group tt-magneto-group does correctly get setup but the task fails given the above error.

**Comment by mpdehaan** [comment]
Can you please share what version of Ansible you are using?

Thanks!

**Comment by mpdehaan** [comment]
Also, can you please file this over at https://github.com/ansible/ansible-modules-core , since this relates to a module?

Thank you!
