### ISSUE TITLE
RFE: Getting azure hosts doesn't return hosts but cloud services

### ISSUE THREAD

**Issue by jruix** [ansible/ansible#9615]
##### Summary:

In Azure, hosts are all inside a cloud service ( behind a load balancer ) and they share the same FQN so in order to access to one host or another the load balancer maps a public port from the public IP to the port 22 of the internal host's private ip.

Using Ansible Tower when adding an inventory based on Azure as SRC, it connects to azure and it gets the cloud services FQN correctly , but not the hosts. Seems that Ansible Tower think that the cloud service is in fact the host, I guess this is because the way Azure works is slightly different from AWS where all hosts has a public dns name.
##### Steps To Reproduce:

In Ansible tower Add an Inventory group using Azure as source
##### Expected Results:

I expect to get a group with all the hosts located in azure
##### Actual Results:

I got a group with all the cloud services in azure but not the hosts

**Comment by mpdehaan** [comment]
Hi, for ansible Tower questions please email support@tower.com -- thank you!

**Comment by jruix** [comment]
They asked me to fill a issue in the github repo :-/, seems we got an infinite loop here ;)
