### ISSUE TITLE
playbook_dir not available for include in devel branch (19606afe5f)

### ISSUE THREAD

**Issue by mfriedenhagen** [ansible/ansible#9618]
##### Ansible Version: 1.8 (devel 19606afe5f)

```
    ansible-playbook 1.8 (devel 19606afe5f) last updated 2014/11/25 08:20:50 (GMT +200)
        lib/ansible/modules/core: (detached HEAD fbc4ed7a88) last updated 2014/11/25 09:29:11 (GMT +200)
        lib/ansible/modules/extras: (detached HEAD e64751b0eb) last updated 2014/11/25 09:29:25 (GMT +200)
        v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/25 09:28:25 (GMT +200)
        v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/25 09:28:36 (GMT +200)
        configured module search path = None

```
##### Summary:

Ansible is not be able to resolve `{{playbook_dir}}` when including a task file from another role.
##### Steps To Reproduce:

Sample at https://github.com/mfriedenhagen/ansible-no-playbookdir

Given you checked out `ansible` to `../ansible` _and_ initialized submodules please run:

```
    virtualenv -p /usr/bin/python venv
    . venv/bin/activate/
    pip install ../ansible # to get dependencies
    . ../ansible/hacking/env-setup
    ansible-playbook --version
    ansible-playbook 1.8 (devel 19606afe5f) last updated 2014/11/25 08:20:50 (GMT +200)
        lib/ansible/modules/core: (detached HEAD fbc4ed7a88) last updated 2014/11/25 09:29:11 (GMT +200)
        lib/ansible/modules/extras: (detached HEAD e64751b0eb) last updated 2014/11/25 09:29:25 (GMT +200)
        v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/25 09:28:25 (GMT +200)
        v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/25 09:28:36 (GMT +200)
        configured module search path = None
```
##### Expected Results:

Output of `ansible-playbook -i hosts -c local playbook.yml` with 1.7.2

```
    PLAY [Show playbook_dir] ****************************************************** 

    GATHERING FACTS *************************************************************** 
    ok: [127.0.0.1]

    TASK: [a | Do stuff] ********************************************************** 
    ok: [127.0.0.1] => {
        "msg": "Hallo"
    }

    TASK: [a | Do stuff in a::foo] ************************************************ 
    ok: [127.0.0.1] => {
        "playbook_dir": "/Users/mifr/workspace/foss/ansible-no-playbookdir"
    }

    TASK: [b | Do stuff in a::foo] ************************************************ 
    ok: [127.0.0.1] => {
        "playbook_dir": "/Users/mifr/workspace/foss/ansible-no-playbookdir"
    }

    TASK: [debug var=playbook_dir] ************************************************ 
    ok: [127.0.0.1] => {
        "playbook_dir": "/Users/mifr/workspace/foss/ansible-no-playbookdir"
    }

    PLAY RECAP ******************************************************************** 
    127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

Running: `ansible-playbook -i hosts -c local playbook.yml` now ends with:

```
    ERROR: file could not read: /Users/mifr/workspace/foss/ansible-no-playbookdir/roles/b/tasks/{{playbook_dir}}/roles/a/tasks/foo.yml
``
```

**Comment by abadger** [comment]
also reported here: https://github.com/ansible/ansible/issues/9621

**Comment by mpdehaan** [comment]
@abadger -- this is likely not the same issue as playbook_dir should not be at inventory scope.   It may be that it is, but it should be generally available.

**Comment by abadger** [comment]
Reproduced.  Looking into what could be happening.

**Comment by abadger** [comment]
The other issues might be intended but it looks like this is caused by the same commit.  Commit 9a0f8f0 which fixed #9498 has the problem while its parent does not.

**Comment by abadger** [comment]
@jimi-c suggested a fix for this.  Hopefully it should sovle your issue!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by majidaldo** [comment]
problem is back with version 2.0.0

**Comment by jimi-c** [comment]
@majidaldo just pushed 0b16580567c3a796487c9e848ff2623363ab6380 to address that.

Thanks!
