### ISSUE TITLE
Variables from var files are not properly expanded

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#9621]
##### Ansible Version:

ansible 1.8 (devel d36c38c35e) last updated 2014/11/25 13:43:44 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 10ebcccedb) last updated 2014/11/25 13:45:21 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2014/11/25 13:45:27 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/11/25 13:45:32 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/11/25 13:45:38 (GMT +200)
  configured module search path = /usr/share/ansible

According to git bisect, the bug was introduced with commit 9a0f8f015877e8f1ae3c728a035120a25d4e7fa9 used to fix #9498
##### Summary:

Variables from var files are not properly expanded.
##### Steps To Reproduce:

```
mkdir './vars'
mkdir './playbooks'
mkdir './handlers'
cat > './files' <<EOF
EOF
cat > './vars/global.yml' <<EOF
basedir: "{{ lookup('env','ANSIBLE_PUBLIC_BASEDIR') }}"
handlers: "{{ basedir }}/handlers"
EOF
cat > './playbooks/example.yml' <<EOF

---
- hosts: example
  vars_files:
    - "{{ lookup('env', 'ANSIBLE_PUBLIC_BASEDIR') }}/vars/global.yml"
  handlers:
      - include: "{{ handlers }}/restart_services.yml"
EOF
cat > './handlers/restart_services.yml' <<EOF
EOF
ANSIBLE_PUBLIC_BASEDIR=$PWD ansible-playbook playbooks/example.yml
```
##### Expected Results:

```
PLAY [example] **************************************************************** 
skipping: no hosts matched

PLAY RECAP ******************************************************************** 
```
##### Actual Results:

```
ERROR: file could not read: /home/till/ansible-bug/playbooks/{{ handlers }}/restart_services.yml
```

**Comment by abadger** [comment]
Looks like this is also reported here: https://github.com/ansible/ansible/issues/9618

**Comment by mpdehaan** [comment]
This is a misunderstanding because the variable is inventory scope, and inventory scoped variables cannot be used in includes.

Feel free to stop by ansible-project list if you have questions about this.

Thanks!

**Comment by tyll** [comment]
On Tue, Nov 25, 2014 at 11:01:08AM -0800, Michael DeHaan wrote:

> This is a misunderstanding because the variable is inventory scope, and inventory scoped variables cannot be used in includes.

It worked until the referenced commit 9 days ago broke it. Also it is
used like this in a lot of playbooks for example from the Fedora
project:
https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/playbooks/groups/anitya.yml

Also why are the variables in "inventory scope" when they are not
defined in the inventory but the playbook via vars_files?

**Comment by jimi-c** [comment]
Hi @tyll, I just tried your example on the devel branch, after fixing a related issue (which was showing the same error message earlier today), and it appears that fix also resolved your issue:

<pre>
# ANSIBLE_PUBLIC_BASEDIR=$PWD ansible-playbook playbooks/example.yml
PLAY [example] **************************************************************** 
skipping: no hosts matched
PLAY RECAP ******************************************************************** 
</pre>

Could you please confirm if you're still seeing the issue with your playbooks?

**Comment by tyll** [comment]
On Mon, Dec 01, 2014 at 08:01:15PM -0800, James Cammarata wrote:

> Hi @tyll, I just tried your example on the devel branch, after fixing
> a related issue (which was showing the same error message earlier
> today), and it appears that fix also resolved your issue:
> 
> Could you please confirm if you're still seeing the issue with your playbooks?

Thank you very much, it looks good now. So it looks like commit:29d41bb
fixes this. Does the code mean that variables defined from vars and
file_vars in a playbook are considered to be in "host" scope and can be
used in defines? I am asking to be able to write a patch for

http://docs.ansible.com/playbooks_variables.html#variables-defined-in-inventory

Regards
Till

**Comment by jimi-c** [comment]
@tyll no, the `vars:` and `vars_files:` playbook entries are not considered inventory-scope (though `group_vars/*` and `host_vars/*` are). This was broken by the fact that we are now trying to avoid merging all of the variable sources together early on, which has caused problems with variable precedence. However, there are still some parts of the code which relied on everything being squashed down into one dict early, which the above patch addressed.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
