### ISSUE TITLE
A particular jinja construct doesn't evaluate to a list anymore in 1.8-devel

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#9622]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 8e7447962e) last updated 2014/11/25 11:12:10 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 10ebcccedb) last updated 2014/11/25 11:12:10 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2014/11/25 11:12:10 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 09:23:36 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 09:23:40 (GMT +200)
  configured module search path = /usr/share/ansible

Worked fine in 1.7.2
##### Environment:

Ubuntu 14.04 on management host
##### Summary:

I'm using a the result of a difference between two lists in a loop:

`java_all_packages|difference([java_pkg])`
##### Steps To Reproduce:

This debug output shows the values of each variable:

```
TASK: [packages/java | debug var=java_pkg] ************************************ 
Tuesday 25 November 2014  15:52:18 +0100 (0:00:00.025)       0:00:02.722 ****** 
ok: [tomcathost] => {                                                           
    "java_pkg": "oracle-java7"                                                  
}                                                                               

TASK: [packages/java | debug var=java_all_packages] *************************** 
Tuesday 25 November 2014  15:52:18 +0100 (0:00:00.115)       0:00:02.838 ****** 
ok: [tomcathost] => {                                                           
    "java_all_packages": [                                                      
    ¦   "sun-java6-bin",                                                        
    ¦   "sun-java6-jdk",                                                        
    ¦   "sun-java6-jre",                                                        
    ¦   "sun-java5",                                                            
    ¦   "sun-java6",                                                            
    ¦   "sun-java7",                                                            
    ¦   "oracle-java7",                                                         
    ¦   "oracle-java8"                                                          
    ]                                                                           
}                                                                               

```
##### Expected Results:

A list with all items except `oracle-java7`
##### Actual Results:

Ansible yields an error on the result not being a list when used in a with_items_loop:

`fatal: [tomcathost] => with_items expects a list or a set`

Please note that adding the `list` filter like this, doesn't help here:

`java_all_packages|difference([java_pkg])|list`

**Comment by bcoca** [comment]
So I 'reverse engineered' your play:

```
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    - java_pkg: "oracle-java7"
    - java_all_packages:
        - "sun-java6-bin"
        - "sun-java6-jdk"
        - "sun-java6-jre"
        - "sun-java5"
        - "sun-java6"
        - "sun-java7"
        - "oracle-java7"
        - "oracle-java8"
  tasks:
#    - debug: var=java_pkg
#    - debug: var=java_all_packages
    - debug: var=item
      with_items: java_all_packages|difference(java_pkg)
```

which outputs:

```
ok: [localhost] => (item=java_all_packages|difference(java_pkg)) => {
    "item": "java_all_packages|difference(java_pkg)"
}
```

or if I change to 'listifying java_pkg':

```
with_items: java_all_packages|difference([java_pkg])
```

I get 

```
fatal: [localhost] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting 
```

tested with 1.7.2 and I get:

```

ok: [localhost] => (item=sun-java6-bin) => {
    "item": "sun-java6-bin"
}
ok: [localhost] => (item=sun-java6-jdk) => {
    "item": "sun-java6-jdk"
}
ok: [localhost] => (item=sun-java6-jre) => {
    "item": "sun-java6-jre"
}
ok: [localhost] => (item=sun-java5) => {
    "item": "sun-java5"
}
ok: [localhost] => (item=sun-java6) => {
    "item": "sun-java6"
}
ok: [localhost] => (item=sun-java7) => {
    "item": "sun-java7"
}
ok: [localhost] => (item=oracle-java8) => {
    "item": "oracle-java8"
}
```

in both cases

**Comment by srgvg** [comment]
FYI, not sure if related, but this reminded me of #8141, #7534 and linked.

**Comment by drybjed** [comment]
And more related bugs: https://github.com/ansible/ansible/issues/9335, https://github.com/ansible/ansible/issues/9369

**Comment by bcoca** [comment]
traced it down to b18bd6b98edecda1fcb5a85053593e78b46b9709 , we are looking into it

**Comment by bcoca** [comment]
@srvg, @drybjed can you test my PR fixes the issue?

**Comment by drybjed** [comment]
@bcoca Got an error, `fatal: [test] => lookup plugins have to return a list: None` - is this something new? Seeing it for the first time. Here's the task that tripped it: https://github.com/debops/ansible-apt/blob/master/tasks/install_packages.yml#L3-L9

**Comment by bcoca** [comment]
@drybjed that is what happens when you 'correct' more than one thing in a patch ;-)
yes, this patch also makes sure settings passed to main template function are passed to recursive calls to it, including filter errors

**Comment by drybjed** [comment]
<del>I just tried on current `devel` and I have completely different issue, which however is further down than the above:</del>

**Comment by bcoca** [comment]
looking at how my patch should work with with_flattened in this case

the ')' seems like a different issue, also my patch is not in devel yet.

**Comment by drybjed** [comment]
OK, my previous error was mistake in my code, disregard that.

**Comment by srgvg** [comment]
+1 I can confirm  #9626 solves this issue for me. Thanks @bcoca

**Comment by bcoca** [comment]
closing as PR was merged

**Comment by srgvg** [comment]
This bug was reintroduced by 5b3c82f4ba550eaf3fafbc95334ffb0e8b02bdf5 in 1.8.1
Solved in devel.
