### ISSUE TITLE
mysql_user module is not idempotent

### ISSUE THREAD

**Issue by time-palominodb** [ansible/ansible#963]
To reproduce, set up a Master and a Slave. On the Master, issue:

```
 action: mysql_user name=root  password=whatevs  host=%  priv=*.*:ALL
```

Do it again. Now the slave will have broken replication with this error:

```
 Last_SQL_Error: Error 'Operation CREATE USER failed for 'root'@'%'' on query. Default database: 'mysql'. Query: 'CREATE USER 'root'@'%' IDENTIFIED BY 'whatevs''
```

The problem is that errors, although not fatal on the masters, will replicate to slaves, where the error cannot be completely determined as normal or abnormal, and replication dies. Thus errors are not idempotent when replicated to the slaves, and "CREATE USER" is such a command.

The equivalent idempotent command is "GRANT" - if you GRANT privileges to a MySQL user, and that user doesn't already exist, then the user is created. So:

```
grant <privilege> on <database>.<table> to 'user'@'host' identified by 'password'
```

is the idempotent equivalent of ensuring the user is present and has the privileges listed.

If you don't want to grant any privilieges (aka priv= wasn't specified), you can just grant the "connect" privilege. The user can connect but not do anything. I'll take a stab at fixing this.

**Comment by time-palominodb** [comment]
oops.

**Comment by mpdehaan** [comment]
so it was ok?

**Comment by time-palominodb** [comment]
Well I submitted the issue to the wrong project (or did I?), so I whacked
it. mysql_user (create) is truly not idempotent.

To fix, change:
cursor.execute("CREATE USER %s@%s IDENTIFIED BY %s", (user,host,password))
to:
cursor.execute("GRANT USAGE ON _._ TO %s@%s IDENTIFIED BY %s", (user,host,
password))

The former, if you execute multiple times on a server will result in ERRORs
and, if the statement is somehow successful on master but via replication
errors out on slaves, it will break replication to slaves (it just happened
to me). The latter statement will achieve the former and will not fail if
the user already exists.

I'm currently testing with my own setup to be 100% sure the latter line
Actually Works.

On Wed, Aug 29, 2012 at 1:18 PM, Michael DeHaan notifications@github.comwrote:

> so it was ok?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/963#issuecomment-8139562.

## 

_Tim Ellis_ | _CTO, PalominoDB_
calendar: https://tungle.me/timellis
phone/sms: +506 6042-5795 / 510-761-6610 | alert: timeless.phone@gmail.com
skype: time_palominodb | email/gtalk: time@palominodb.com
yim: time.palominodb@yahoo.com | aim: time@palominodb.com

**Comment by mpdehaan** [comment]
this was the correct project.  Feel free to reopen -- pull request for the fix would be great.  Thanks for spotting/fixing/testing!

**Comment by time-palominodb** [comment]
I will submit the pull request. Note that the command IS idempotent from
Ansible's POV, because the module:

<ec2-50-112-223-80.us-west-2.compute.amazonaws.com> REMOTE_MODULE
mysql_user name=root  password=whatevs  host=%  priv=_._:ALL
ok: [ec2-50-112-223-80.us-west-2.compute.amazonaws.com] => {"changed":
false, "user": "root"}

That is, Ansible notices the "root" user already exists, so there's only
one very unusual case that I just happened to run into, where I tried to
create the user on my whole cluster, the user got created on the slaves
first, then the master, then the statement replicated to the slaves, where
it then killed replication due to user already existing.

On Wed, Aug 29, 2012 at 1:21 PM, Michael DeHaan notifications@github.comwrote:

> this was the correct project. Feel free to reopen -- pull request for the
> fix would be great. Thanks for spotting/fixing/testing!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/963#issuecomment-8139656.

## 

_Tim Ellis_ | _CTO, PalominoDB_
calendar: https://tungle.me/timellis
phone/sms: +506 6042-5795 / 510-761-6610 | alert: timeless.phone@gmail.com
skype: time_palominodb | email/gtalk: time@palominodb.com
yim: time.palominodb@yahoo.com | aim: time@palominodb.com

**Comment by marktheunissen** [comment]
Why are you running the statement on your slaves before the master? For that matter, why even run it directly on the slaves at all? 

It is idempotent, as it will check if the user exists before attempting to create it. 

I think you're going to run into more problems - for example, using mysql_db - creating a database on the slaves first is also going to fail when the master tries to replicate, surely?

But, it certainly wouldn't hurt to change it to the GRANT syntax, if that works just as well, and possibly add IF NOT EXISTS to the CREATE DATABASE in mysql_db, however yours is a very edgy case. :)

**Comment by time-palominodb** [comment]
> ...yours is a very edgy case. :)
> 
> I at first assumed the same as you, I've hit a bizarre edge case. You have
> to write your playbook to create the user cluster-wide (on master+slaves)
> after replication is set up for the error to happen.

Then on the other hand, maybe this isn't such an edge case. Replication is
common. Thinking to do X across your whole cluster is common. Forgetting
the implicit "I do this on master it happens on slaves" is common. We can't
cover every case where someone does something like this, but this is easy
to fix, so why not?

The GRANT syntax creates the user if they don't already exist. I also like
adding the "if not exists" to the create database. Once I fork Ansible and
patch it I'll submit the pull request.

## 

_Tim Ellis_ | _CTO, PalominoDB_
calendar: https://tungle.me/timellis
email/gtalk: time@palominodb.com | skype: time_palominodb
yim: time.palominodb@yahoo.com | aim: time@palominodb.com
phone/sms: +506 6042-5795 / 510-761-6610 | alert: timeless.phone@gmail.com

**Comment by marktheunissen** [comment]
Great, thanks! :)

**Comment by trevoro** [comment]
Was this issue actually resolved or was it closed?
I'm seeing some other non idempotent issues with the mysql module and I'm more than willing to submit a pull request.

**Comment by Oneiroi** [comment]
@trevoro from the code digging I've been doing in #6049 (formerly #5633) this code has not changed and the CREATE syntax is still in use at this time; as it is an edge case as @time-palominodb pointed out, I assume that's the reason for a lack of patch submission.

**Comment by hdra** [comment]
Sorry for bringing up an old thread, but may I know whats the status of this?

I am currently having a problem with the mysql_user module with ansible v.1.5.3.

Basically I am trying to change the mysql root password like whats discussed in this SO thread: http://stackoverflow.com/questions/16444306/ansible-idempotent-mysql-installation-playbook

But it seems like ansible keeps trying to create a user for root@ansible_hostname even though that user already exists. The problem is gone when I remove ansible_hostname from the list of hosts.

**Comment by time-palominodb** [comment]
Top answer looks good.

## 

_Tim Ellis:_ 510-761-6610

**Comment by hdra** [comment]
Um, no, I realized that. I was asking idempotency of the mysql_user module, since it seems like ansible keeps trying to create a user for root@{{ ansible_hostname }} even though the user already exists.

**Comment by time-palominodb** [comment]
I suspect the module is still broken. What should happen is it should
"select count(*) from mysq.user where user=root and
host='{{ansible_hostname}}" and if result is >0, then do nothing.

## 

_Tim Ellis:_ 510-761-6610

**Comment by hdra** [comment]
I see. Is there any chance to get this issue re-opened? I'll see if I can confirm the issue, and if it is, I'll try to work on a fix.

Strange thing is, it works just fine with the localhost, 127.0.0.1 and ::1 host.

**Comment by time-palominodb** [comment]
I certainly don't object to this issue being reopened, but IIRC the project
maintainers closed it in the first place, and I didn't really care that
much.

These days I do all my DB admin outside Ansible due to momentum probably
started with issues like this.

## 

_Tim Ellis:_ 510-761-6610

**Comment by jimmykane** [comment]
Same issue here @hdra . 
@mpdehaan This issue should be reopened

**Comment by zytek** [comment]
+1

**Comment by VladimirDaniyan** [comment]
+1

**Comment by nicolas-g** [comment]
+1

**Comment by gardner** [comment]
+1

**Comment by deepshikhagandhi** [comment]
+1

**Comment by ErrorProne** [comment]
+1

**Comment by martindines** [comment]
+1

**Comment by ghost** [comment]
Another problem with this module:
if you want just to change the mysql root pw, you get this error:
Operation CREATE USER failed for 'root'@'localhost'

I guess this is not fixed by commit: https://github.com/flori/ansible-modules-core/commit/aa19a5780df385b60fde823aab2807202dfdf9ad

:edit: updating the mysql password used to work in old ansible version, I'm not 100% sure, but I guess it worked in 1.7 - 1.9 (not really sure about the exact version numbers, but it _did_ work somewhere in the past)

HTH
