### ISSUE TITLE
play stopped after reboot in RHEL/CentOS 7

### ISSUE THREAD

**Issue by shirou** [ansible/ansible#9632]
##### Issue Type:

Bug Report
##### Ansible Version:
- 1.8 release
- 1.7.2
##### Environment:
- RedHat Enterprise 7
- CentOS 7
##### Summary:

Reboot and wait for comes up the server in one playbook on RHEL/CentOS 7, the plays is stopped. It does not occured in RHEL/CentOS 7. I tried openssh and paramiko connection. but both is same.

I have sent an Email on Mailing list, https://groups.google.com/forum/#!msg/ansible-project/Oqt3pMht1n4/zb9bYkNW4BEJ
and got an answer about this problem is fixed on the devel. But on the 1.8 release, it seems still alive.
##### Steps To Reproduce:

play this playbook.

```
- hosts: all
  sudo: yes
    - name: reboot
      shell: /sbin/reboot
    - name: wait for the server to go down (reboot)
      local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
    - name: wait for the server to come up
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
    - debug: msg="rebooted!"
```
##### Expected Results:

play continues.
##### Actual Results:

stop at first reboot task.

```
TASK: [reboot] ****************************************************************
failed: [54.xxx.xxx.xxx] => {"failed": true, "parsed": false}
SUDO-SUCCESS-zyufvisfwxfaiyxcktsvkbsubavkwknx

FATAL: all hosts have already failed -- aborting
```

**Comment by keithchambers** [comment]
I spent a lot of time finding a working solution. This play works for me on CentOS 7 / RHEL7:  https://github.com/keithchambers/microservices-playground/blob/master/playbooks/upgrade-packages.yml

**Comment by shirou** [comment]
Thank you!  It works for me. 

I tried some combination.
- bash -c "sleep 2s && reboot"
  - BAD
- nohup bash -c "sleep 2s && reboot"
  - BAD
- bash -c "sleep 2s && reboot" & 
  - looks OK but not rebooted actually
- nohup bash -c "sleep 2s && reboot" &
  - OK

**Comment by mpdehaan** [comment]
You'll need to use async actions with the pause module.

As this is not a bug, but more of a user question, please stop by ansible-project list if you'd like to discuss methods.

Thanks!
