### ISSUE TITLE
Ansible setup module is not working under Suse Enterprise Linux  11 (SLES11)

### ISSUE THREAD

**Issue by jsetzer** [ansible/ansible#9634]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8
##### Environment:

Suse Enterprice Linux Server 11 SP3 (SLES11SP3) 64 Bit 
##### Summary:

I have found an issue in ansible 1.8:
When I use setup module under Suse Enterprose Linux it brings be other results as ansible 1.7:

machine data is :

uname -a
Linux suse02i 3.0.101-0.35-default #1 SMP Wed Jul 9 11:43:04 UTC 2014 (c36987d) x86_64 x86_64 x86_64 GNU/Linux

cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
##### Steps To Reproduce:

ansible -m setup -i ~/ansible_hosts all | grep dist
##### Expected Results:

ansible 1.7:
command:
ansible -m setup -i ~/ansible_hosts all | grep dist
        "ansible_distribution": "Suse",
        "ansible_distribution_major_version": "11",
        "ansible_distribution_release": "3",
        "ansible_distribution_version": "11",
        "facter_lsbdistcodename": "n/a",
        "facter_lsbdistdescription": "SUSE Linux Enterprise Server 11 (x86_64)",
        "facter_lsbdistid": "SUSE LINUX",
        "facter_lsbdistrelease": "11",
        "facter_lsbmajdistrelease": "11",
##### Actual Results:

ansible 1.8:
command:
pdmadm22@suse02i:~> ansible -m setup -i ~/ansible_hosts all | grep dist
        "ansible_distribution": "Suse",
        "ansible_distribution_major_version": "11",
        "ansible_distribution_release": "x86_64",
        "ansible_distribution_version": "11",
        "facter_lsbdistcodename": "n/a",
        "facter_lsbdistdescription": "SUSE Linux Enterprise Server 11 (x86_64)",
        "facter_lsbdistid": "SUSE LINUX",
        "facter_lsbdistrelease": "11",
        "facter_lsbmajdistrelease": "11",

In Ansible 1.7 SLES SP3 is shown in ansible_distribution_release, in ansible 1.8 is does not work anymore:

I had allready mailed this bug a few days ago, but in final 1.8 it is stil present
I have created the following patch:

``` patch
diff --git a/lib/ansible/module_utils/facts.py b/lib/ansible/module_utils/facts.py
index 5ceeb40..dbcdc5d 100644
--- a/lib/ansible/module_utils/facts.py
+++ b/lib/ansible/module_utils/facts.py
@@ -328,9 +328,18 @@ class Facts(object):
                                     self.facts['distribution_release'] = release.groups()[0]
                                     break
                             elif path == '/etc/SuSE-release':
+                                linuxdist = platform.linux_distribution()[0]
+                               matchEnterprise = re.match( r'.*Enterprise.*' , linuxdist , re.I )
+                               if matchEnterprise:
+                                        matchObj = re.match( r'.*Server.*', linuxdist , re.I)
+                                       if matchObj:
+                                               self.facts['distribution'] = "SLES";
                                 data = data.splitlines()
                                 for line in data:
-                                    release = re.search('CODENAME *= *([^\n]+)', line)
+                                   if matchEnterprise:
+                                       release = re.search('PATCHLEVEL *= *([^\n]+)', line)
+                                   else:
+                                       release = re.search('CODENAME *= *([^\n]+)', line)
                                     if release:
                                         self.facts['distribution_release'] = release.groups()[0].strip()
                                         break
```

now it works under ansible 1.8 as expected again:
ansible -m setup -i ~/ansible_hosts all | grep dist
        "ansible_distribution": "SLES",
        "ansible_distribution_major_version": "11",
        "ansible_distribution_release": "3",
        "ansible_distribution_version": "11",
        "facter_lsbdistcodename": "n/a",
        "facter_lsbdistdescription": "SUSE Linux Enterprise Server 11 (x86_64)",
        "facter_lsbdistid": "SUSE LINUX",
        "facter_lsbdistrelease": "11",
        "facter_lsbmajdistrelease": "11",

can you please check this ?
--> I need the correct SP value in ansible_distribution_realse and ansible_distribution should be SLES unter SLES  in all of my ansible scripts

**Comment by bcoca** [comment]
can you submit this as  PR?

**Comment by jsetzer** [comment]
Hi Brian,

how should I do this ?

Kind regards
Joachim

Von: Brian Coca [mailto:notifications@github.com]
Gesendet: Mittwoch, 26. November 2014 16:07
An: ansible/ansible
Cc: Setzer, Joachim
Betreff: Re: [ansible] Ansible setup module is not working under Suse Enterprise Linux 11 (SLES11) (#9634)

can you submit this as PR?

**Comment by bcoca** [comment]
The docs on how to contribute:
http://docs.ansible.com/community.html#contributing-code-features-or-bugfixes

**Comment by Jmainguy** [comment]
Consider checking out https://github.com/ansible/ansible/pull/9440 as well

**Comment by abadger** [comment]
@jsetzer I see that https://github.com/ansible/ansible/pull/9440 was merged.  Did that fix this issue as well?

**Comment by abadger** [comment]
Appears wasn't fixed since @alxgu opened that PR :-)   I see that the PR wants to use SLES for SuSE Enterprise Linux but the expectation at the top of this bug report is that we'd use SuSE.  Is there some consensus that can be reached?

**Comment by alxgu** [comment]
IMHO is the fact "ansible_distribution": "Suse" for a SLES system wrong.
Suse is the os_family for openSuse and SLES/SLED 
-> http://upload.wikimedia.org/wikipedia/commons/4/46/SuSE_family_tree_11-06.png

But for the fact "distribution" I need it more precisely, it should distinguish between the enterprise and non-enterprise distribution.
@jsetzer does it fit your requirements?

**Comment by Jmainguy** [comment]
Is there any easy way to get sles setup to test it? I tried some docker images, but none of them let me change password so I could have ansible ssh in and run setup

**Comment by alxgu** [comment]
You have to fill out a form to get a 60-days trial version of SLES.
https://www.suse.com/products/server/download/?s_gaevent=Homepage%257CIntro%257CSUSE

**Comment by Glandos** [comment]
Or just simply go there : https://download.novell.com/index.jsp?product_id=&search=Search&bu=suse&families=2658&version=42045&date_range=&date_start=16+Feb+2015&date_end=16+Feb+2015&keywords=&sort_by=&results_per_page=

And Select the desired architecture in the bottom list. Novell only provides ISOs images, so you need to install it in VirtualBox or similar. You may need to register to be able to download the images.

I am deeply insteresting in fixing this bug and merging the related PR, since it affects me. I rely on PATCHLEVEL detection to do a lot of work…
Given the huge differences between OpenSuse and SuSE Linux Enterprise, it should be great to separate the detection for those two platform.

**Comment by alxgu** [comment]
@Glandos did you test my PR?

**Comment by Glandos** [comment]
@alxgu I did (against Ansible 1.8.2), and it works fine when I try to gather facts from 270 servers, mixing SLES10SP2, SP3, SP4 and SLES11SP3.
Thanks a lot!

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/10128/ now merged.  Feel free to open a new ticket if there's still more enhancements to be made to the detection of  Suse family distirbutions.  Thanks @alxgu for creating the fix.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by jpmens** [comment]
This patch does not work on SLES 10 because its Python 2.4's `platform` doesn't have `linux_distribution()`.  A simple workaround, is to replace

``` python
linuxdist = platform.linux_distribution()[0]
```

in the above patch, by

``` python
try:
    linuxdist = platform.linux_distribution()[0]
except:
    linuxdist = platform.dist()[0]
```

**Comment by bcoca** [comment]
@jpmens, if you have the time, could we get that in a PR?

**Comment by jpmens** [comment]
Sorry, can't do that from this environment.

**Comment by alxgu** [comment]
@jpmens this PR is needless. The issue should be fixed with the merged PR https://github.com/ansible/ansible/pull/10128 -  without the platform library
