### ISSUE TITLE
Relative file lookup inside roles no longer works

### ISSUE THREAD

**Issue by jheino** [ansible/ansible#9637]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8
##### Environment:

Debian 7.0 "wheezy"
##### Summary:

I have a file stored as roles/mariadb/files/mariadb.gpg. Using the lookup plugin to read its contents no longer works when using a relative path inside the role. It used to work in 1.7.2 but not anymore in 1.8.0.
##### Steps To Reproduce:

Put a file in roles/mariadb/files/mariadb.gpg. Then run a playbook that utilizes the mariadb role.

The contents of roles/mariadb/tasks/main.yml:

```

---
- debug: msg="{{ lookup('file', 'mariadb.gpg') }}"
```

The contents of the playbook:

```

---
- hosts: all
  roles:
  - mariadb
```
##### Expected Results:

The contents of the mariadb.gpg file.
##### Actual Results:

```
TASK: [mariadb | debug msg=""] ************************************************
ok: [192.168.100.39] => {
    "msg": ""
}
```

**Comment by mpdehaan** [comment]
We have tests for exactly this but will validate.  Thanks for the report!

**Comment by jheino** [comment]
After further inspection, it seems that relative paths fail to work anywhere. The only way I can get the file lookup plugin to work is to use an absolute path:

```
jukka@atom:~/ansible-bug$ echo 'Testing, 1 2 3' > helloworld.txt
jukka@atom:~/ansible-bug$ /home/virtualenv/bin/ansible -m debug -a "msg=\"{{ lookup('file', 'helloworld.txt') }}\"" -i ansible_hosts all
192.168.100.39 | success >> {
    "msg": ""
}

jukka@atom:~/ansible-bug$ /home/virtualenv/bin/ansible -m debug -a "msg=\"{{ lookup('file', '/home/jukka/ansible-bug/helloworld.txt') }}\"" -i ansible_hosts all
192.168.100.39 | success >> {
    "msg": "Testing, 1 2 3"
}
```

**Comment by davidfritzsche** [comment]
I think the problem originates in the change in `utils.listify_lookup_plugin_terms()`. It tries to expand the content (as before in Ansible 1.7.2), but it now throws (with default settings) an exception if this does not work and I guess you do not have a variable `mariadb.gpg`. The exception is then silenced in `template.lookup()`.

I find it surprising and counter-intuitive that Ansible tries to expand the lookup argument as if it is a variable name, i.e., it runs `{{mariadb.gpg}}` through the template machinery. I would have expected that it runs `mariadb.gpg` (which is then just a raw string and does not get expanded) through Jinja2.

**Comment by bcoca** [comment]
the problem is that it is hard for the lookup plugin to distinguish between these 2 cases:

```
lookup('file', 'myfile')
```

and

```
lookup('file', myfile)
```

In 1.8.0 we introduced a change to fail if myfile (the var) is undefined, but that breaks relative file lookup 'myfile', specially since we allow for double templating of variables (myfile: "{{othervar}}").

working on a fix.

**Comment by davidfritzsche** [comment]
If I understand correctly how Jinja2 works, the `myfile` argument in

```
lookup('file', myfile)
```

gets expanded by Jinja2 before the Ansible lookup funtion is called. To test it I've inserted a simple print statement into the `utils.template.lookup()` function and then ran the following playbook:

```
---
- hosts: somehost
  vars:
    myfile: 'foo/bar'
  tasks:
    - copy:
        content: "{{ lookup('file', myfile) }}"
        dest: "/tmp/foo"
```

the produced output of the `print` in `template.lookup()` is

```
lookup('file', args=('foo/bar',), kwargs={...})
```

(output of kwargs shortened as it is huge and not relevant for the problem)

If I use `lookup('file', 'myfile')` instead, the output is then

```
lookup('file', args=('myfile',), kwargs={...})
```

How about adding some kind of quoting to the terms passed to the lookup plugin when called from `utils.template.lookup()`? I experimentally changed the code from

```
            ran = instance.run(*args, inject=vars, **kwargs)
```

to

```
            ran = instance.run(*["'%s'" % a for a in args], inject=vars, **kwargs)
```

and it worked surprisingly well and should not interfere with `with_*` loops. I'm pretty sure that this does not cover all cases, but it may by a direction worth investigation.

**Comment by bcoca** [comment]
@davidfritzsche  that looks better than the road i was following, testing it now

**Comment by davidfritzsche** [comment]
@jheino : For the time being `lookup('file', './mariadb.gpg')` is likely going to work, i.e., start the relative path with `./`. That worked for me.

**Comment by mpdehaan** [comment]
auto-quoting the vars needs to take into account the concept that lookup plugins are also used for iterators, so be careful with that :)

**Comment by davidfritzsche** [comment]
@mpdehaan Yes, I notices that the plugins are also used for loops. Surprised my at first, but is actually a nice feature ;-)
From my understanding the Python function `utils.template.lookup()` is only used when Jinja2 expands an actual lookup function call and is not used for iterators. If this is not the case (i.e. the function is also used for loops) then my quoting suggesting is definitely not going to work correctly.

**Comment by bcoca** [comment]
the above merge should fix
