### ISSUE TITLE
[bug][regression] variables read by debug, not used in other modules

### ISSUE THREAD

**Issue by gangelop** [ansible/ansible#9649]
##### Issue Type:

bug
##### Ansible Version:

```
ansible 1.8.1
  configured module search path = None
```
##### Environment:

from: Archlinux
against: OpenBSD 5.5
##### Summary:

ansible doesn't seem to use `ansible_python_interpreter` variable, even though it reads it, according to `debug` module. This is a regression from `ansible 1.7.2`
##### Steps To Reproduce:

Use a `hosts` file, similar to the following. Host `192.168.1.5` doesn't have a `/usr/bin/python2` executable, but has `/usr/local/bin/python2.7`

```
192.168.1.5 ansible_python_interpreter="/usr/local/bin/python2.7" ansible_ssh_user="root"
```

Run these:

```
ansible -vvv -i hosts -m debug all -a "var=ansible_python_interpreter"
ansible -vvv -i hosts -m ping all
```
##### Expected Results:

Successful execution of both commands
##### Actual Results:

```
# ansible -vvv -i hosts -m debug all -a "var=ansible_python_interpreter"
<192.168.1.5> ESTABLISH CONNECTION FOR USER: root
192.168.1.5 | success >> {
    "ansible_python_interpreter": "/usr/local/bin/python2.7"
}

# ansible -vvv -i hosts -m ping all                                     
<192.168.1.5> ESTABLISH CONNECTION FOR USER: root
<192.168.1.5> REMOTE_MODULE ping
<192.168.1.5> EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/george/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 192.168.1.5 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python2'
192.168.1.5 | FAILED >> {
    "failed": true, 
    "msg": "/bin/sh: /usr/bin/python2: not found\n", 
    "parsed": false
}
```

**Comment by bcoca** [comment]
can you specify the OS? installation method? can you show the shebang line of the ping module?

**Comment by gangelop** [comment]
##### Environment:

from: Archlinux
against: OpenBSD 5.5

Ansible installation method is [archlinux package](https://www.archlinux.org/packages/community/any/ansible/)

```
george@morpheus ~ % head -n1 /usr/lib/python2.7/site-packages/ansible/modules/core/system/ping.py
#!/usr/bin/python2
```

**Comment by bcoca** [comment]
So the problem is that the shebang is incorrect, this is probably an issue with the archlinux package. The ansible_python_interpreter matches '/usr/bin/python' (as it is in the ansible repo) to do substitution but not '/usr/bin/python2'.

**Comment by gangelop** [comment]
I changed the shebang to `#!/usr/bin/python` and the `ping` module works now.
I've opened an [archlinux bug](https://bugs.archlinux.org/task/42941).
