### ISSUE TITLE
ansible_python_interpreter inventory var not works as expected

### ISSUE THREAD

**Issue by dss09** [ansible/ansible#9650]
## Issue Type:

Bug Report
## Ansible Version:

ansible 1.8.1
  configured module search path = /usr/share/ansible
## Environment:

Running OS: Arch
Managing OS: CoreOS
## Summary:

ansible_python_interpreter inventory variable not works as expected. 
It doesn`t change python interpreter for shell, command modules ...
## Steps To Reproduce:

hosts:

```
ubuntu-test1 ansible_ssh_user=core ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
```

test.yml:

``` yaml
- hosts: ubuntu-test1
  gather_facts: False
  tasks:
    - raw: "/home/core/bin/python --version"
    - debug: msg="Python {{ ansible_python_interpreter }}"
    - command: "echo {{ ansible_python_interpreter }}"
```
## Expected Results:

```
PLAY [ubuntu-test1] *********************************************************** 

TASK: [raw /home/core/bin/python --version] *********************************** 
ok: [ubuntu-test1] => {"rc": 0, "stderr": "", "stdout": "/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\n/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\nPython 2.7.8 (f5dcc2477b97, Sep 18 2014, 11:33:30)\r\n[PyPy 2.4.0 with GCC 4.6.3]\r\n"}

TASK: [debug msg="Python {{ ansible_python_interpreter }}"] ******************* 
ok: [ubuntu-test1] => {
    "msg": "Python PATH=/home/core/bin:$PATH python"
}

TASK: [command echo {{ ansible_python_interpreter }}] ************************* 
ok: [ubuntu-test1] => {"rc": 0, "stderr": "", "stdout": "PATH=/home/core/bin:$PATH python"\r\n"}
```
## Actual Results:

```
PLAY [ubuntu-test1] *********************************************************** 

TASK: [raw /home/core/bin/python --version] *********************************** 
ok: [ubuntu-test1] => {"rc": 0, "stderr": "", "stdout": "/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\n/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)\r\nPython 2.7.8 (f5dcc2477b97, Sep 18 2014, 11:33:30)\r\n[PyPy 2.4.0 with GCC 4.6.3]\r\n"}

TASK: [debug msg="Python {{ ansible_python_interpreter }}"] ******************* 
ok: [ubuntu-test1] => {
    "msg": "Python PATH=/home/core/bin:$PATH python"
}

TASK: [command echo {{ ansible_python_interpreter }}] ************************* 
failed: [ubuntu-test1] => {"failed": true, "parsed": false}
/bin/sh: /usr/bin/python2: No such file or directory


FATAL: all hosts have already failed -- aborting
```

**Comment by dss09** [comment]
same as #9649

**Comment by bcoca** [comment]
instead of :
ansible_python_interpreter="PATH=/home/core/bin:$PATH python"

use:
ansible_python_interpreter=/home/core/bin/python

I don't know the particular linker that CoreOS uses but I would not expect path variables in the shebang to work.

also the ' /usr/bin/python2' suggests that you have incorrect shebang lines in the modules on the 'master'

**Comment by dss09** [comment]
Thanks for the answer, 
I`ve changed it, but it doesn`t work.
The same answer:

```
failed: [ubuntu-test1] => {"changed": false, "failed": true, "parsed": false}
/bin/sh: /usr/bin/python2: No such file or directory
```

**Comment by bcoca** [comment]
As I stated in last line of my previous comment, I suspect the shebang on the command module is incorrect.. Check it on your 'master' and confirm.

**Comment by dss09** [comment]
Yes, I have the same problem, as in #9649.

```
$ head -n1 /usr/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
#!/usr/bin/python2
```

will wait for [arch bug](https://bugs.archlinux.org/task/42941) fix ... 

Thanks.

**Comment by lad1337** [comment]
sorry to trigger this again...
we have run into this problem too with an addition

some facts:
- we run ansible-playbook from OSX
- all hosts are CoreOS `CoreOS 1010.4.0 (MoreOS)`
- we used `defunctzombie.coreos-bootstrap` as a ansible-galaxy requirement (which was run previously)
- we set `ansible_python_interpreter: "PATH=/home/core/bin:$PATH python"`

this creates a similar error:

``` json
{
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "/home/core/pypy/bin/pypy: /lib64/libssl.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
/home/core/pypy/bin/pypy: /lib64/libcrypto.so.1.0.0: no version information available (required by /home/core/pypy/bin/pypy)
Traceback (most recent call last):
  File \"app_main.py\", line 75, in run_toplevel
  File \"/home/core/.ansible/tmp/ansible-tmp-1464942169.86-141751627413624/setup\", line 114, in <module>
    exitcode = invoke_module(module, zipped_mod, ZIPLOADER_PARAMS)
  File \"/home/core/.ansible/tmp/ansible-tmp-1464942169.86-141751627413624/setup\", line 28, in invoke_module
    p = subprocess.Popen(['PATH=/home/core/bin:$PATH python', module], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
  File \"/home/core/pypy/lib-python/2.7/subprocess.py\", line 710, in __init__
    errread, errwrite)
  File \"/home/core/pypy/lib-python/2.7/subprocess.py\", line 1331, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

_now_ this does not happen on my colleges machine (ansible-2.0.2.0)
but it does happen on mine (ansible-2.1.0.0) it does work if ansible_python_interpreter is changed to `/home/core/bin/python` as @bcoca suggested

**Comment by arthur-c** [comment]
Same problem with ansible 2.1, CoreOS and pypy from defunctzombie. I reverted to stable-2.0 and it's ok. I run Ansible from Fedora.

**Comment by weemen** [comment]
I reverted to stable 2.0 as well for the reason as @arthur-c

**Comment by abadger** [comment]
This is a closed issue so it's unlikely that any one will see it who can
fix it.  Please open a new issue or comment on an open issue with these
symptoms if one exists.

A superficial look suggests that the issues reported here may be the same
as reported in this pull request:
https://github.com/ansible/ansible/pull/16247

**Comment by roytruelove** [comment]
Making [this change](https://github.com/ansible/ansible/issues/9650#issuecomment-64901287):

```
ansible_python_interpreter: "PATH=/home/core/bin:$PATH python"
```

to

```
ansible_python_interpreter=/home/core/bin/python
```

_AND_ upgrading to 2.2.x solved this for me.  Making this change while on 2.1.x did _not_ work.

**Comment by tedder** [comment]
^ For the record, I can't get @roytruelove's version to work. If the PATH is removed I get "ImportError: No module named ansible". After adding the path back, I get the `OSError: [Errno 2] No such file or directory` error in subprocess.py. It appears to be an issue with the pipes in subprocess.

**Comment by dotemacs** [comment]
Just like @roytruelove & @bcoca before him, I couldn't get it to work as:

> ansible_python_interpreter="PATH=/home/core/bin:$PATH python"

but could, with: 

> ansible_python_interpreter=/home/core/bin/python

This is with ansible **2.4.1.0** on OSX, with CoreOS **1235.12.0**

**Comment by abadger** [comment]
it's not expected that most systems would understand trying to set an environment variable inside of a shebang line.  ansible_python_interpreter is set to what will show up inside of the shebang line.  if you are finding documentation somewhere out on the wider internet that says to set the ansible_python_interpreter to include PATH, then you should have them correct it.

I'm going to lock this issue as it's been closed for a long time and it's only by chance that I happened to see new comments on it.  In general, closed issues are not looked at which leads to frustration when people do not get a reply.  If you have an issue using ansible_python_interpreter in the correct manner, please open a new issue for us to take a look at.  Thank you.
