### ISSUE TITLE
npm with --save-dev flag

### ISSUE THREAD

**Issue by vacquah** [ansible/ansible#9653]
Confused about how to run something like this with ansible ( especially the --save-dev flag part). Do I manually create a package.json file in my project root directory before using ansible to install the npm package?

```
npm install gulp-ruby-sass --save-dev
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
