### ISSUE TITLE
Bug: "module setup not found in configured module paths" for Windows hosts with Ansible 1.8.1

### ISSUE THREAD

**Issue by ibratoev** [ansible/ansible#9659]
##### Issue Type:

Bug Report
##### Ansible Version:

Official 1.8.1, installed with pip.
ansible 1.8.1
  configured module search path = None
##### Environment:

Running from ubuntu 14.04
Managing Windows 2008 R1
##### Summary:

During a Gathering Facts phase I get this error for any Windows hosts.

```
module setup not found in configured module paths.  Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.
```
##### Steps To Reproduce:

Run a playbook targeting Windows with gather_facts enabled.
##### Expected Results:

The GATHERING FACTS phase to pass successfully.
##### Actual Results:

module setup not found in configured module paths.

**Comment by ibratoev** [comment]
Running the play with `gather_facts: false` works just fine.

**Comment by ibratoev** [comment]
I think this cries for 1.8.2...

**Comment by ajmalshaikh** [comment]
I am getting error same as above as failed": true, "msg": "The module sitefacts.py was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."}
