### ISSUE TITLE
Add elasticache "parameter_group" parameter to elasticache module

### ISSUE THREAD

**Issue by aangov** [ansible/ansible#9661]
Hi,

Just an idea/feature request that would be really useful if you want to manage almost everything related to Elasticache through Ansible.

It would be really useful to have the parameter "parameter_group" for the Cache Parameters Groups on Elasticache. 

When creating a cache cluster right now there is no way to choose a different parameter group than the default one, instead you have to use the AWS managment console to do this.

**Comment by aangov** [comment]
Hi, I think this should go to ansible-modules-core instead, I can reopen it there if you want to close it here.

Thanks.

**Comment by bcoca** [comment]
closing in favor of https://github.com/ansible/ansible-modules-core/issues/432

**Comment by aangov** [comment]
Hi, I ll reopen this in ansible-modules-core since it's related to the "parameter_group" parameter.

**Comment by aangov** [comment]
Opened issue:
https://github.com/ansible/ansible-modules-core/issues/436

**Comment by raben2** [comment]
support my pull request for params module https://github.com/ansible/ansible-modules-extras/pull/1156
