### ISSUE TITLE
cannot express host pattern that is a group slice

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#9670]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

N/A
##### Summary:

Host pattern to do list slicing does not work. As described in http://docs.ansible.com/intro_patterns.html one should be able to express:

```
hosts: db[1:5]
```

or

```
hosts: db[1:]
```

but this will result in no hosts found.
##### Steps To Reproduce:

```
~/src/derp> cat hosts
[db]
host1
host2
~/src/derp> cat test.yaml

---
- name: test hosts
  hosts: db[1:]
  tasks:
    - name: do something
      debug: msg="do something"
~/src/derp> ansible-playbook -i hosts test.yaml --list-hosts

playbook: test.yaml

  play #1 (test hosts): host count=0
```
##### Expected Results:

host2 should have been selected. It's the one you'd get from expressing db[1:] as it's the only item in the list other than the first one.

```
~/src/derp> ansible-playbook -i hosts test.yaml --list-hosts

playbook: test.yaml

  play #1 (test hosts): host count=1
    host2
``

##### Actual Results:

No hosts are selected. This is due to a line in lib/ansible/inventory/__init__.py in def get_hosts(self, pattern="all"):
```

```
    patterns = pattern.replace(";",":").split(":")
```

```
The pattern passed in is "db[1:]" which will get split into
"db[1" and "]" which is obviously not going to work.

Searching history, seems this has been the case for quite a while, so I'm confused how this ever worked.
```

**Comment by cscetbon** [comment]
I'm :+1: and currently it doesn't raise any error at all except that hosts are not picked as expected

**Comment by cscetbon** [comment]
in the meantime as a workaround we can use the pattern [x-y] instead of [x:y] which is supported at https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py#L271-L272

**Comment by cscetbon** [comment]
Unfortunately, it's not working as expected even if the regex seems correct, so you can forget this workaround : 

```
PLAY [Test mygroup[0-1]] ****************************************************

GATHERING FACTS ***************************************************************
ok: [10.0.1.237]

PLAY [Test mygroup[0]:mygroup[1]] *****************************************

GATHERING FACTS ***************************************************************
ok: [10.0.1.237]
ok: [10.0.1.238]
```

**Comment by willthames** [comment]
@cscetbon 
first digit: 0-based index of host in group - so 0 for first host
second digit: index + 1 of host that you desire

so if your group looks like: 

```
[desiredhosts]
host1
host2
host3
host4
```

and you want hosts 3 and 4 then you need to use `desiredhosts[2-4]`

This is definitely weird and unexpected behaviour.

**Comment by cscetbon** [comment]
@willthames This is really weird (using an index out of bound). In python saying [x:y] means from x to y-1, but [x-y] has always meant from x to y. So ansible has its proper definitions !

**Comment by willthames** [comment]
My major issue with this is that the tests don't match the documentation

http://docs.ansible.com/intro_patterns.html
conflicts with
https://github.com/ansible/ansible/blob/60f972dfe4bc58180c666f820ef2d602acf917e4/test/units/TestInventory.py#L212

If I were to add in a test that matches the docs, it would fail. 

Looking at the commit introducing the test (which also changed the parsing) it was done by @jimi-c in response to bug #4620 

That issue also mentions http://docs.ansible.com/playbooks_best_practices.html

> What about just the first 10, and then the next 10?:
> 
> ansible-playbook -i production webservers.yml --limit boston[0-10]
> ansible-playbook -i production webservers.yml --limit boston[10-20]

Which is unexpected (I would think 1-10 and 11-20 would be a nicer way of specifying the first 10 and the second 10). 

Anyway, there is a bug somewhere - even if only in the documentation of patterns at:
http://docs.ansible.com/intro_patterns.html

Hopefully @jimi-c can weigh in on this as I'm really not sure of the best 'fix'.

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
