### ISSUE TITLE
Fact caching docs don't mention gathering=smart

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#9671]
##### Issue Type:

Documentation Report
##### Ansible Version:

```
ansible 1.8.1
  configured module search path = None
```
##### Environment:

N/A
##### Summary:

The [documentation on fact gathering](http://docs.ansible.com/playbooks_variables.html#fact-caching) doesn't say anything about the advantages of setting `gathering=smart` in your ansible.cfg file in conjunction with fact gathering.

If you do this, and don't explicitly specify `gather_facts` in your plays, then (apparently) Ansible will only gather facts if the fact cache is empty or stale.

**Comment by abadger** [comment]
It is listed here: https://github.com/ansible/ansible/blob/devel/docsite/rst/intro_configuration.rst#gathering  but I could see where it could be good to have more information next to the fact gathering section itself.  Would you have time to work on a pull request to add some of that information or a pointer to that section?
