### ISSUE TITLE
sudo fails on "--" on SLES10

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#969]
The sudo program on Suse SLES10 fails when invoked with the "--" via Paramiko (and probably SSH) connections. I've removed the double dash in Ansible 0.6 `lib/ansible/runner/connection/paramiko_ssh.py` and nothing appears to break.

Can that be removed permanently or will it break on other platforms?

(Haven't tested w/ connection=ssh but the issue probably exists there too...)

**Comment by mpdehaan** [comment]
Pretty sure we've already removed this on 0.7.

Send me a pull request to the release branch and we can apply that change
there as well.

**Comment by jpmens** [comment]
Rats. I should have checked: yes, it's gone in current devel.

Thank you.

(I won't bother w/ the pull request.)
