### ISSUE TITLE
Dynamic Inventory should have implicit localhost and/or Empty inventory files shouldn't be an error

### ISSUE THREAD

**Issue by follower** [ansible/ansible#9712]
##### Issue Type:

Bug Report / Feature Idea
##### Ansible Version:

ansible 1.8.1
##### Environment:

N/A
##### Summary:

Since the introduction of implicit localhost with `local_action` it is legitimate to want to run a playbook with an empty inventory file.

At present an empty inventory file or an empty dynamically generated inventory (e.g. from `ec2.py` in the situation where no EC2 instances exist/running) triggers an error--even if the only plays are for `local_action`.

The "accepted" workaround when not using dynamic inventory seems to be to supply `-i 'localhost,'` but this is apparently not recommended practice. Additionally, this also requires the use of `ansible_connection=local` to work around an "issue" with `synchronize` trying to log onto `localhost` via ssh.

It appears a "better" workaround is to supply a completely invalid IP in the inventory list as this case is handled explicitly (via https://github.com/ansible/ansible/issues/5820, https://github.com/ansible/ansible/commit/f955d9db6a01c6d5c2cd761b3bdfd76ae20de86b and https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory/__init__.py#L360) and does not require a workaround for `synchronize`. e.g.

```
ansible-playbook  -i '999.999.999.999,' playbook.yml
```

There appears to be no workaround to this situation when using dynamic inventory and even if an explicit `localhost` entry was added to the inventory it would complicate the use of the `all` parameter for `hosts:`.

It seems like with the addition of implicit localhost, the commit https://github.com/ansible/ansible/pull/1628/files (see https://github.com/ansible/ansible/blob/devel/bin/ansible-playbook#L162) should now either be reversed and/or have the same special implicit localhost handling that the "undocumented" approach gained with https://github.com/ansible/ansible/commit/f955d9db6a01c6d5c2cd761b3bdfd76ae20de86b.

It is possible that in some situations it would still be appropriate to issue a warning in the case of an empty inventory (e.g. if there are no `local_actions` in the playbook).

As it stands both these situations are a hinderance to "green fields" deployment situations which as a "first use" situation seems like an important thing to get right. (Equally if for some reason all your VMs have been terminated...by a bad `exact_count` bug for example. :) )

The issue specifically in relation to dynamic inventory is mentioned in https://github.com/ansible/ansible/issues/6442 but this seems to have been buried.

Thanks!
##### Steps To Reproduce:
1. Run the following against an EC2 account with no VMs running:
   
   ```
   ansible-playbook -i plugins/inventory/ec2.py playbook.yml
   ```
   
   The playbook should have `local_action` commands to set up VMs. e.g. http://docs.ansible.com/guide_aws.html#example-4
##### Expected Results:

An EC2 instance should be created etc.
##### Actual Results:

```
ERROR: provided hosts list is empty
```

**Comment by the2hill** [comment]
This is reproducible, and would like to see this fixed. My work around is to include a 'base' inventory file and load it as such:

```
ansible-playbook -i plugins/inventory/ playbook.yml
```

The base inventory file contains a simple localhost reference:

```
[base]
localhost   ansible_connection=local
```

**Comment by bcoca** [comment]
closed via merged patch
