### ISSUE TITLE
Ability to use dot notation in inventory files

### ISSUE THREAD

**Issue by mgcrea** [ansible/ansible#9718]
##### Issue Type:

Feature Idea
##### Ansible Version:

```
$ ansible --version
ansible 1.8.1
```
##### Environment:

```
$ uname -a
Darwin 0x6D67 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```
##### Summary:

nested vars can't seem to be set in inventory files 
##### Steps To Reproduce:

```
player-foo ansible_ssh_host=player-3979.local player.name="foo"
```
##### Expected Results:

Properly override fact:

```
{player: {name: "foo"}}
```
##### Actual Results:

```
{player: {name: "bar"}, "player.name": "foo"}
```

**Comment by quixoten** [comment]
:+1:

**Comment by bcoca** [comment]
for that you should really use host_vars/group_vars, ini parsing of nested vars is 'messy' at best

**Comment by mpdehaan** [comment]
Variables need to use "{{ foo }}" inside the values and do recursively evaluate.  Please stop by ansible-project list if you'd like to discuss.

Thanks!
