### ISSUE TITLE
Implement su_exe feature

### ISSUE THREAD

**Issue by E-M** [ansible/ansible#9724]
**Issue Type:**
Feature Idea

**Ansible Version:**
N/A

**Environment:**
Linux

**Summary:**
Consider to implement su_exe feature for alternative su implementations, just like there is already sudo_exe feature for alternative sudo implementations. More info: https://groups.google.com/forum/#!searchin/ansible-project/sesu/ansible-project/CC1x7yvi3X4/gr-nK2WElaIJ

**Steps To Reproduce:**
N/A

**Expected Results:**
Ansible supports su_exe config parameter in ansible.cfg

**Actual Results:**
su_exe not implemented yet

**Comment by mpdehaan** [comment]
we're working on having something for support of things like powerbroker soon - and a bit more generic.  Please stay tuned!
