### ISSUE TITLE
 Show variable on name in playbooks / roles

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9725]
When I run playbooks, and I have defined several variables, I'd like to see that the variables can be used in the names of each task as well.
## For example:

vars: 
-  foo: bar
- name: You can order drinks in a {{ foo }}
  command: /usr/bin/drinkdrinks.sh

Should give the output:
"You can order drinks in a bar". [changed]

Instead it gives:
You can order drinks in a {{ foo }} [ changed]

In other words; it would be nice if Ansible would use the declared variables values instead of the variable name in the "-name"  section of the task.

**Comment by bcoca** [comment]
ansible does use it if the variable is available, the problem comes with
host/inventory/fact variables that are host dependent and cannot be
resolved at the time of the task name resolution. If you use play/extra
vars it should work, take into account that task names must be the same for
all hosts in the task.

## 

Brian Coca

**Comment by ahamilton55** [comment]
@bcoca : I'm seeing this issue too. It used to work but no longer does. I currently pass in a "service_name" variable with -e to the ansible-playbook command and it doesn't get updated in any of the task names.

For example:

``` bash
TASK: [deploy | Copy over the {{ service_name }} package] *********************
```

I also have a bunch of group variables that also don't get updated to the names. It seems like the names aren't run through the template function any longer.

I'm also running against the latest devel.

**Comment by WilcoE** [comment]
i agree, its a nice feature and i hope it wil be possible in a newer update

**Comment by mpdehaan** [comment]
Variables in task scope can't be resolved like you ask because they could differ for each of 500 different hosts.

Please stop by ansible-project if you'd like to discuss or need some more help on this one.  Thanks!
