### ISSUE TITLE
Surprising quoting behavior in parser

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#9728]
I would like to preface this issue by stating that I consider it low priority, but am raising it because of seemingly curious behavior.

I'm using the command module to POST a JSON payload using curl. The curl command works on the command line: 

```
curl -X POST -d '{"source":"http://couchdb.example.org:5984/products","target":"products","create_target":true}' -H 'Content-Type: application/json' http://localhost:5984/_replicate
```

However, it errors when in Ansible:

```
command: curl -X POST -d '{"source":"http://couchdb.example.org:5984/locations","target":"locations","create_target":"true"}' -H "Content-Type: application/json" http://localhost:5984/_replicate
```

> There seems to be an extra unquoted colon in the line
> and this is confusing the parser. It was only expecting to find one free
> colon. The solution is just add some quotes around the colon, or quote the
> entire line after the first colon.

Pointing at the colon in the content type : `Content-Type:`

To work around this, I tried wrapping the entire line in single quotes, escaping the inner single quotes: 

```
command: 'curl -X POST -d \'{"source":"http://couchdb.example.org:5984/locations","target":"locations","create_target":true}\' -H "Content-Type: application/json" http://localhost:5984/_replicate'
```

> It seems that there is a value started
> with a quote, and the YAML parser is expecting to see the line ended
> with the same kind of quote.

Pointing at the beginning of the payload : `\'{`

Which I believe to be an error, as the line starts, and is terminated by, a single quote.  I believe that the correct approach would be addressing the last approach (handling escaped quote characters) in ansible/utils/**init**.py's process_common_errors().

Alternatively (and likely more controversially), what about a "quoting" character that allows for passing commands in their raw format and leaves it to the host to process the command? e.g. 

```
command: ___curl -X POST -d \'{"source":"http://c....}\' -H "Content-Type: application/json" http://localhost:5984/_replicate___
```

Side note: I'm aware that the URI module could be used to send payloads, but I don't want to install its dependencies on the target boxes.

**Comment by mpdehaan** [comment]
Quoting shell commands can be an interesting thing.

Please stop by ansible-project if you'd like to discuss some tips and ways to simplify (like using the uri module).

Thanks!
