### ISSUE TITLE
Ansible 1.7.2, module: file. Can't set permissions on hardlinks.

### ISSUE THREAD

**Issue by iprok** [ansible/ansible#9734]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Gentoo amd64
##### Summary:

Can't set permissions on hardlinks using file module
##### Steps To Reproduce:

file: path=<some hardlink path> owner=root group=sudo mode=4710
##### Expected Results:

Permissions will be set correctly

Actual Results:
error:
msg: src and dest are required for creating links

I think it's totally wrong cause hardlinks are also regular files.

**Comment by mpdehaan** [comment]
Hi, the current ansible version is 1.8.2, can you please test there and reopen if you see problems on the current version.

Thanks!
