### ISSUE TITLE
Background task has different job ids on different hosts

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#9740]
##### Issue Type:

Bug Report

(behavior inconsistent with docs)
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

N/A
##### Summary:

Docs say background tasks get some job id on all servers, but the ids are different.
##### Steps To Reproduce:

Run a command on multiple servers in the background. For example:

```
ansible all -s -m apt -a upgrade=safe -B 3600 -P 0
```
##### Expected Results:

The [docs](http://docs.ansible.com/intro_adhoc.html#time-limited-background-operations) say "The same job ID is given to the same task on all hosts", so I expected the returned `ansible_job_id` to be the same for each server.
##### Actual Results:

Returned ansible job ids are different:

```
queue | success >> {
    "ansible_job_id": "488359678239.2844",
    "results_file": "/root/.ansible_async/488359678239.2844",
    "started": 1
}

web | success >> {
    "ansible_job_id": "488359678239.2453",
    "results_file": "/root/.ansible_async/488359678239.2453",
    "started": 1
}

database | success >> {
    "ansible_job_id": "488359678239.2500",
    "results_file": "/root/.ansible_async/488359678239.2500",
    "started": 1
}
```

**Comment by mpdehaan** [comment]
The last number is actually the pid, so I consider this a place where we just need to clarify the docs.

Thanks for the report.

**Comment by mpdehaan** [comment]
(I'd suggest just removing this line from the docs).
