### ISSUE TITLE
Ansible 1.7.2, module: cron. Crontabs aren't added when delegating to host.

### ISSUE THREAD

**Issue by iprok** [ansible/ansible#9742]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Ansible on Gentoo amd64. Cron on ubuntu trusty 14.04.
##### Summary:

Trying to add crontabs on my backup server for group of hosts. No all crontabs are added. Seems that simultaneously added crontabs overwrite each other.
##### Steps To Reproduce:

  cron: name="Backup of mysql db from {{ inventory_hostname }}" state=present user=srvbackup
        minute="0"
        hour="0"
        job="{{ BackupMasterBackupRoot }}/mysql_backup.sh {{ ExternalSSHHost }} {{ ExternalSSHPort }}"
  delegate_to: backupmaster
##### Expected Results:

For group of for example four hosts four crontab records should be added with the first run.
##### Actual Results:

Ansible reports changes on all hosts, but really we have only part of crontabs.

serial: 1 
in the play helps, but it's only workaround.

**Comment by mpdehaan** [comment]
The current version of Ansible is 1.8.X, if you see the problem there, please reopen this issue on the github.com/ansible/ansible-modules-core repo (which is the modules repo).

Thank you!
