### ISSUE TITLE
Unarchive fails to unzip .zip file; must be an existing dir

### ISSUE THREAD

**Issue by Jonnymcc** [ansible/ansible#9747]
##### Issue Type:

“Bug Report”
##### Ansible Version:

Ansible version = 1.6.1
##### Environment:

Host: Ubuntu 14.04
Target: Ubuntu 12.04
##### Summary:

I get the following error, `'/home/ec2-api-tools' must be an existing dir`. If I SSH into the box and unzip the file and then again try running the playbook the unzip task succeeds and the result indicates a change.

Related? #6723 #6790
##### Steps To Reproduce:

```
- name: Download EC2 API tools
  get_url: url=http://s3.amazonaws.com/ec2-downloads/ec2-api-tools.zip dest=/home/ec2-api-tools.zip mode=0440

- name: Unzip EC2 API tools
  unarchive: src=/home/ec2-api-tools.zip dest=/home/ec2-api-tools copy=no
```
##### Expected Results:

The ec2 api tools zip unzipped into the /home/ec2-api-tools directory.
##### Actual Results:

It is not unzipped.

**Comment by mpdehaan** [comment]
Sounds like this is not a bug, but an error where it is requesting for you to create the dir where you are downloading first with the file module (state=directory).

If you would like to discuss further, please stop by the ansible-project list.

Thanks!
