### ISSUE TITLE
Feature: Please add fromjson() filter for Jinja2: patch inline

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#975]
I'm looking at register variables, and would like to propose a one-line change to `lib/ansible/utils.py` to support JSON output.
### The patch

```
diff --git a/lib/ansible/utils.py b/lib/ansible/utils.py
index 65bc704..4b5461e 100644
--- a/lib/ansible/utils.py
+++ b/lib/ansible/utils.py
@@ -242,6 +242,7 @@ def template_from_file(basedir, path, vars):

     environment = jinja2.Environment(loader=jinja2.FileSystemLoader(basedir), trim_blocks=False)
     environment.filters['tojson'] = json.dumps
+    environment.filters['fromjson'] = json.loads
     data = codecs.open(path_dwim(basedir, path), encoding="utf8").read()
     t = environment.from_string(data)
     vars = vars.copy()
```

This patch allows us to return JSON into a register-variable:
### Playbook

```
  - name: Run jpprog.sh
    action: command ./jpprog.sh
    register: v

  - name: Populate template
    action: template src=${filename} dest=/tmp/out
```
### jpprog.sh

```

#!/bin/sh

cat <<!
{
    "number": 18,
        "name": "john"
}
!
exit 0
```
### Template

```
{% set t = v.stdout|fromjson %}

JSON struct T: {{ t }}

name = {{ t.name }} 
number = {{ t['number'] }} 
```
### Output

```
JSON struct T: {u'number': 18, u'name': u'john'}

name = john 
number = 18 
```

Good idea? :-)

**Comment by mpdehaan** [comment]
If v.stdout returns JSON, you basically could run the script as a module.   Though that's totally fine if you don't.  I need to see about exposing other things to Jinja, like getattr as you mentioned elsewhere.

I'll accept this, send me a PR -- though I think both fromjson and tojson should be from_json and to_json to be consistent with the rest of the API.
