### ISSUE TITLE
major slow down in task execution with large inventory (1.9-devel and 1.8.2) 

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#9753]
##### Issue Type:

Bug
##### Ansible Version:

1.9-devel and 1.8.2

Bisect leads to 29d41bb789383c3ff59269b28877ea0f270f5861 which is also cherry-picked in 1.8.2
##### Environment:

Ubuntu 14.04 + 12.04
##### Summary:

Ansible became very slow in task exectution, compared to earlier versions.
##### Steps To Reproduce:

The extra time is obvious (amongst others) in a template task.
_One needs a large inventory with many variables before this becomes noticeable._
Test with a simple play that gather facts and has 1 template task, that contaians e.g. {{ ansible_env }} from the facts,
##### Expected Results:

Task executes in less than a second
##### Actual Results:

Task executes in less than in to 6-7 seconds

**Comment by abadger** [comment]
Note -- the work in v2 is going to change how we manage variables quite a bit.  So this may be something that we revisit after we have that working.

**Comment by srgvg** [comment]
To give a slight idea on how big inventory and vars are here:

```
$ ansible 'all[0]' -m debug -a var="hostvars[inventory_hostname]" |wc -l
76971
```

**Comment by jimi-c** [comment]
@srvg going through old issues, and I believe we resolved this didn't we?

**Comment by bcoca** [comment]
since both versions are not supported and we have other tickets about performance on the current version, i'm going to close this
