### ISSUE TITLE
lookup('file' should have option to santise imput

### ISSUE THREAD

**Issue by ciphernaut** [ansible/ansible#9761]
##### Issue Type:

Bug Report/Feature Idea
##### Ansible Version:

1.8.1
##### Environment:

Fedora 19
##### Summary:

Sourced variable has issues with content containing " (and probably : " also)

The lookup('file'   function should provide an option to sanitise input making it compatible with output elsewhere.

The current setup makes it What You Mean Is What You Get  requiring additional handling for " and possibly : also.  The sanitation option would allow one to set it What You See Is What You Get  and let ansible handle modifying to \" and {{":"}} for more transparent use.
##### Steps To Reproduce:

Consider myplaybook.yml:
vars:
- announcement_content: "{{ lookup('file', 'outage-announce-banner.txt') }}"
  tasks: 
- name: set announce banner
                lineinfile: dest=/var/www/html/myapp/params
                regexp="._announcehtml._"
                line="           'announcehtml' => '{{ announcement_content }}',"

outage-announce-banner.txt:

<div style="background-color: yellow;">This service will upgraded at 0:00 UTC 2014-12-24.</div>

##### Expected Results:

playbook can do lineinfile with "   and not require \"
##### Actual Results:

the playbook bombs out

**Comment by bcoca** [comment]
filters are meant for data transformation, lookups are just for gathering data.

lookup(..)| changedata|changedatagain

So we won't implement this in a lookup but would welcome a filter that does the work you want.

**Comment by ciphernaut** [comment]
the direct way is:

```
- announcehtml_content: "{{ lookup('file', 'outage-announce-banner.txt')|replace('\"','\\\"') }}"
```

the alternative reusable way is via filter plugin as you suggested:

```
- announcehtml_content: "{{ lookup('file', 'outage-announce-banner.txt')|inputSantise }}"
```

with plugin inputSanitise.py: 

```
import string
def inputSanitise(content):
    ''' convert to lineinfile compatible output '''
    return string.replace(content, '"', '\"')

class FilterModule(object):
    def filters(self):
        return {
    'inputSanitise' : inputSanitise
  }
```

Kudos @willthames

**Comment by willthames** [comment]
It's also important to use lineinfile correctly. When line isn't trivial and looks at all like it might be yaml (e.g. it contains a colon), then you should probably use lineinfile with `args` (this is reasonably well documented for `set_fact` but I still spent half a day into digging into why `set_fact` wasn't behaving as expected, and then noticed it in the docs!)

```
- name: set announce banner 
  lineinfile: dest=/var/www/html/myapp/params regexp=".announcehtml." 
  args: 
    line: "      'announcehtml' => '{{ announcement_content }}',"
```
