### ISSUE TITLE
digital ocean inventory still uses old per host lookup

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#9774]
##### Issue Type:

Bug report.
##### Ansible Version:

ansible 1.7.2
##### Environment:

My workstation:
Mac OS X 10.10 Yosemite
python-2.7.6

I'm not "managing" anything yet, I'm new to ansible and I'm just doing tests with inventory scripts. Anyway, the hosts I'm ssh'ing to are Linux (Ubuntu and Amazon AMI).
##### Summary:

If you use multiple dynamic inventory scripts at once, some scripts are run with `--host` for each and every host - not just the hosts they provide, but hosts coming from the other scripts too.
##### Steps To Reproduce:

I've created the `~/ansible/inventory` directory and I've placed there the `ec2.py` and `digital_ocean.py` dynamic inventory scripts, downloaded from `plugins/inventory` on github. I've configured the scripts with my credentials for EC2 and DO.

Testing these scripts manually, they both work just fine.

(Note: before each step below, I delete the caches of both inventory scripts)

Then I do:

```
ansible -i ~/ansible/inventory/ec2.py -u secret-user -f 20 -s \* -m shell -a 'ps'
```

That works fine. Looking at the process tree list while ansible is being executed, I see ansible running `ec2.py --list`, then it launches a big pile of ssh processes. All is well.

Then I do:

```
ansible -i ~/ansible/inventory/digital_ocean.py -u secret-user -f 20 -s \* -m shell -a 'ps'
```

Works fine. I see ansible running `digital_ocean.py --list`, then it runs `digital_ocean.py --host` for each host in the list, then ssh, and I get my results. All is well.

Then I do:

```
ansible -i ~/ansible/inventory -u secret-user -f 20 -s \* -m shell -a 'ps'
```
##### Expected Results:

Fast execution. If any of the inventory scripts is run with `--host`, it should only run for the hosts it provides.
##### Actual Results:

The last step is where things go wrong. The command is completed just fine, overall, but when I look at the process list while it's running, I see this:
- ansible runs one of the scripts with `--list`
- then it runs the other script with `--list`
- then it runs `digital_ocean.py --host` for each and every host, not only for hosts in DO, but for hosts in EC2 as well.

That cannot possibly be correct. First off, it's very slow; it takes a lot of time for the DO script to investigate, unnecessarily, the hosts that actually belong to EC2. Secondly, the DO API servers are doing unnecessary work.

I'm pretty sure `digital_ocean.py --host` should only be executed for the DO hosts.

Note: Not sure if this is related, but one difference between the EC2 and the DO scripts is that the EC2 script actually generates the `"_meta:"` tag at the top of its output, whereas the DO script does not. Regardless, the current behavior should not take place, no matter whether a script generates _meta or not.

**Comment by bcoca** [comment]
it is not wrong, just not optimal, the ec2 script has been updated to return the meta_ with all the inventory variables, the digital ocean script still uses the old method that requires a call per host

**Comment by FlorinAndrei** [comment]
I agree that the DO script should do "_meta". However, I find it a bit odd that Ansible just blindly calls that script with --host for all hosts, not just the hosts that the DO script generates.

Anyway, I've added "_meta" to the DO script and I did a pull request, see above.

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!

**Comment by cchurch** [comment]
@mpdehaan This is not a module issue, it's an issue with the inventory script in this repo.

**Comment by jimi-c** [comment]
# Switch to Proposal

Hi!

As of April of 2016, we have started using the Ansible Proposal process for large feature ideas or changes in current functionality, such as this. Because this issue has been open for so long without any action, we are going to go ahead and close it at this time. If you are still interested in seeing this new feature get into Ansible, please submit a proposal for it using this process.

https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md

If you have any further questions, please let us know by stopping by our devel mailing list, or our devel IRC channel:
- #ansible-devel on Freenode
- https://groups.google.com/forum/#!forum/ansible-devel

Thank you!

**Comment by jimi-c** [comment]
FWIW, we have been talking recently about revamping the dynamic inventory stuff, and providing a general purpose base class for script writers to use, which would provide methods to generate the `_meta` style output automatically.
