### ISSUE TITLE
library/* uses hard-coded #!/usr/bin/python

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#978]
Trying to get ansible nodes with Suse SLES9 running here. On-board Python is 2.3.3 so I'm building Python 2.7.3 and dropping it into /usr/local/python273 with a symlink into /usr/local/bin/python.

I've convinced SSHD to change $PATH which works (tested with `ansible -m raw`), and now I see this won't work (i.e. getting Ansible's modules to use new Python) because `library/*` have hard-coded `#!/usr/bin/python` in them. (0.6 and current git)

Is there any reason _not_ to change that to `#!/usr/bin/env python` for those of us who have to fight with legacy systems? ;-)

**Comment by jpmens** [comment]
`bin/ansible*` uses `#!/usr/bin/env python`

**Comment by jhoekx** [comment]
Put `ansible_python_interpreter: /usr/local/python273` as a variable in your inventory. No path trickery needed!

**Comment by jpmens** [comment]
W000T! How did I miss that?!?
Thank you _very_ much, @jhoekx -- works a treat! :-)
