### ISSUE TITLE
[Ansible 1.8.2] apt.cache.FetchFailedException marks the host as failed

### ISSUE THREAD

**Issue by hpio** [ansible/ansible#9781]
##### Issue Type:

Seems I've encountered a bug when using apt:update_cache module
##### Ansible Version:

piotr@bladerunner:~/workspace/ansible$ ansible --version
ansible 1.8.2
  configured module search path = /usr/share/ansible
##### Environment:

Ansible is running on:

```
piotr@bladerunner:~/workspace/ansible$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

but the host that fails is running:

```
root@testbackend:~# cat /etc/debian_version 
7.7
```
##### Summary:

When apt update_cache returns an error i.e. 404 ansible marks the host as failed
##### Steps To Reproduce:

add the following play to your playbook:

```

---
# file: roles/common/tasks/main.yml
- name: Update APT package cache
  apt: update_cache=yes
```

if one of the repos fails to download Ansible will mark a host as failed
##### Expected Results:

Ansible should continue processing other plays from a playbook
##### Actual Results:

```
failed: [testbackend] => {"failed": true, "parsed": false}
SUDO-SUCCESS-ycccmcgxcutokctlosijkbhgwnzenrec
Traceback (most recent call last):
  File "/home/localadmin/.ansible/tmp/ansible-tmp-1418302810.6-280233863008910/apt", line 2167, in <module>
    main()
  File "/home/localadmin/.ansible/tmp/ansible-tmp-1418302810.6-280233863008910/apt", line 547, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ftp.uk.debian.org/debian/dists/wheezy-updates/main/source/Sources  Bad header line [IP: 78.129.164.123 80]
, W:Failed to fetch http://ftp.uk.debian.org/debian/dists/wheezy-updates/main/binary-amd64/Packages  Bad header line [IP: 78.129.164.123 80]
, W:Failed to fetch http://security.debian.org/dists/wheezy/updates/main/binary-amd64/Packages  404  Not Found [IP: 212.211.132.250 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.
```

```
testbackend                     : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by jimi-c** [comment]
I disagree that this should not be a failure, since you're telling the system to do something and it is failing. However, tracebacks like this are always an error, so we will look into properly catching that.

**Comment by hpio** [comment]
Actually I agree with you, I could have been more specific.
Anyway, marking a host as failed is definitely not a desired state

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
