### ISSUE TITLE
Exit with_items after first success

### ISSUE THREAD

**Issue by hughsaunders** [ansible/ansible#9782]
##### Summary:

Add mechanism for exiting a with_items loop after the first success. Or more generally, the ability to reference the result of the previous iteration in the when: clause for the current iteration. 
##### Steps To Reproduce:

Consider the following scenario: I need to download a file and have a list of possible sources, I want to loop of the list of sources and stop once I have the file. 

This doesn't seem to be possible at the moment, ansible will continue looping till the end of the list. 

```
---$
- hosts: localhost$
  gather_facts: False$
  tasks:$
    - get_url:$
        src: "{{item}}"
        dest: afile
      with_items:$
        - "http://mirror1.com/afile"$
        - "http://mirror2.com/afile"
        - "http://mirror3.com/afile"$
      register: shell_result$
      until: shell_result|success$
      ignore_errors: True$
```
##### Expected Results:

Possible solutions: 
- Add previous_iteration variable for use in when clause, eg `when: previous_iteration | failed`
- Allow registered variable to be used within a loop, eg `when: shell_result['results'][-1].rc != 0`
##### Actual Results:

Loop continues till the end, can't find a way to exit after the first success.

**Comment by mpdehaan** [comment]
This is an interesting feature idea, but let's discuss on the mailing list instead of here.

I'm not sure it's appropriate for ansible.

**Comment by FractalizeR** [comment]
Can you give a link to the discussion on the mailing list to follow? I am also interested in the feature.
