### ISSUE TITLE
run_once tasks are skipped without checking the delegate_to host

### ISSUE THREAD

**Issue by ccciudatu** [ansible/ansible#9784]
##### Issue Type:

Bug report
##### Ansible Version:

1.8
##### Environment:

Any
##### Summary:

As `run_once` will always target the first host in the list, if that host is supposed to skip a set of tasks (due to some condition, for instance), it will also skip any `run_once` tasks even though they may `delegate_to` other hosts which are willing to run that task.
##### Steps To Reproduce:
- A playbook targets a group of hosts (say `host1`, `host2`, `host3`)
- A role in that playbook is applied conditionally (`when: some_flag`).
- `host1` does not have the flag set, while `host2` and `host3` do
- The "regular" tasks within that role are therefore only applied on `host2` and `host3` and are skipped on `host1` (as expected)
##### Expected Results:

In the above scenario, for a task marked with `run_once: yes` and `delegate_to: host2` I would expect it should run (on `host2`), since it does have the flag set
##### Actual Results:

However, the above-mentioned `run_once` task _will also be skipped_ (by `host1`, as it's the first one in the list).

I don't expect this to be the intended behavior (but merely a consequence of the current implementation), as that task which should run only on `host2` has no reason to be skipped.

**Comment by abadger** [comment]
PR merged.  Thanks!

**Comment by weiyu10** [comment]
This bug not fixed, I have a comment in https://github.com/ansible/ansible/pull/9814

**Comment by weiyu10** [comment]
## This is my site.yaml
- hosts: all
  
  tasks:
  - name: debug for run_once and delegate_to
    debug: msg=success
    run_once: True
    delegate_to: "{{ groups['compute'][0] }}"
    when: inventory_hostname in groups['compute']

This is my host
[compute]
compute01

[control]
control01
control02
control03

This is result 

TASK: [debug for run_once and delegate_to] ************************************
skipping: [control01]

PLAY RECAP ********************************************************************
compute01                  : ok=1    changed=0    unreachable=0    failed=0
control01                  : ok=1    changed=0    unreachable=0    failed=0
control02                  : ok=1    changed=0    unreachable=0    failed=0
control03                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by jimi-c** [comment]
@spunkzwy this has been fixed in devel and will be included in 2.0.1. Which version of Ansible are you running?

**Comment by weiyu10** [comment]
@jimi-c thanks
ansible version is 1.9.4, which commit fixed this bug,https://github.com/ansible/ansible/issues/9784 ?

**Comment by jimi-c** [comment]
This was fixed in devel/stable-2.0. It will most likely not be back-ported to 1.9.

**Comment by ccesario** [comment]
@spunkzwy did you find any solution for this problem!?

**Comment by weiyu10** [comment]
@ccesario I didn't any solution for this problem.
