### ISSUE TITLE
Ansible string variable values that contain dashes yield unexpected results when used in a conditional 

### ISSUE THREAD

**Issue by jarv** [ansible/ansible#9786]
##### Ansible Version:

```
$ ansible-playbook --version
ansible-playbook 1.9 (devel f88e2e1f01) last updated 2014/12/11 11:21:42 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 467ad65f73) last updated 2014/12/11 12:44:11 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD b8071a8d5e) last updated 2014/12/11 12:44:13 (GMT -400)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/12/11 12:44:14 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/11 12:44:16 (GMT -400)
  configured module search path = None
```
##### Environment:

Ubuntu 14.04 (N/A)
##### Summary:

Testing the truth value of a string variable should fail, if the variable has dashes in the value it will evaluate as true. 
##### Steps To Reproduce:

Example play:

```
- name: Test play
  hosts: all
  vars:
    with_dash: "a-value-with-dashes"
    without_dash: "without_dashes"
  tasks:
    - debug: msg="with_dash"
      when: with_dash
    - debug: msg="without_dash"
      when: without_dash
```
##### Actual Results:

```
TASK: [debug msg="with_dash"] ************************************************* 
ok: [localhost] => {
    "msg": "with_dash"
}

TASK: [debug msg="without_dash"] ********************************************** 
fatal: [localhost] => error while evaluating conditional: without_dashes
```
##### Expected Results:

```
TASK: [debug msg="with_dash"] ************************************************* 
fatal: [localhost] => error while evaluating conditional: with_dash
```

**Comment by bcoca** [comment]
nevermind, its not the variable, its the value

**Comment by nathancahill** [comment]
There's some history to this bug. We used to use `jinja2.utils.concat` to parse Jinja templates. Values with dashes (and numbers coincidentally) were interpreted as subtraction (see this [bug report](https://github.com/ansible/ansible/issues/4104)).

This lead to a [fix](https://github.com/ansible/ansible/commit/35d138a0d6642536d63926b74260c0ebb8aee441) being put in place to catch this exception. However, once the underlying Jinja interpreting changed to `template.template` with better value handling, the fix stuck around.

Submitting a pull request to undo 35d138a

**Comment by bngsudheer** [comment]
The issue is occurring on  ansible 2.4.2.0 which prevents using the role ansible.install-gcloud. The test case https://github.com/ansible/ansible/issues/9786#issue-51718114 fails.
