### ISSUE TITLE
user module -> group parameter -> sees int as str -> fail with TypeError

### ISSUE THREAD

**Issue by r1k0** [ansible/ansible#9796]
##### Issue Type:

Bug report 
##### Ansible Version:

rik ~ $ ansible --version
ansible 1.8.2
  configured module search path = None
rik ~ $ 

same from latest git code
##### Environment:

running arch and deploying on RH.
##### Summary:

<vsrv1942.int.belbone.be> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rik/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 vsrv1942.int.belbone.be /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user'
failed: [vsrv1942.int.belbone.be] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 3157, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 1532, in main
    (rc, out, err) = user.modify_user()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 600, in modify_user
    return self.modify_user_usermod()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 384, in modify_user_usermod
    ginfo = self.group_info(self.group)
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 463, in group_info
    return list(grp.getgrgid(group))
TypeError: group id must be integer
##### Steps To Reproduce:

oh boy I can't just attach my  config, too big.

To reproduce, use the user module to create a user and specify a gid as in:

``` python
 11 - name: ensure mon user exists
 12   user: name={{ mon_user }} state=present home=/opt/users/{{ mon_user }} group={{ mon_user_gid }} uid={{ mon_user_uid }} shell=/bin/bash password={{ db_password }} update_password=on_create
```

where those variables are defined in main.yaml

``` python
 27 mon_user: icinga
 28 mon_user_gid: 9000
 29 mon_user_uid: 9000
```

There is ONLY an issue with the group parameter, the rest works as expected.
##### Expected Results:

an int is not a string.
##### Actual Results:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 3157, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 1532, in main
    (rc, out, err) = user.modify_user()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 600, in modify_user
    return self.modify_user_usermod()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 384, in modify_user_usermod
    ginfo = self.group_info(self.group)
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 463, in group_info
    return list(grp.getgrgid(group))
TypeError: group id must be integer
##### to fix:

If I change core/system/user.py group_info():

``` python
 459     def group_info(self,group):
 460         if not self.group_exists(group):
 461             return False
 462         if group.isdigit():
 463             return list(grp.getgrgid(group))
 464         else:
 465             return list(grp.getgrnam(group))
```

line 463

``` python
 459     def group_info(self,group):
 460         if not self.group_exists(group):
 461             return False
 462         if group.isdigit():
 463             return list(grp.getgrgid(int(group)))
 464         else:
 465             return list(grp.getgrnam(group))
```
###### extra info

I used 1.8.2 + same results with git clone/pull

I defined in vars/main.yaml:

``` python
 27 mon_user: icinga
 28 mon_user_gid: 9000
 29 mon_user_uid: 9000
```

then in tasks/monitoring_user.yaml:

``` python
 11 - name: ensure mon user exists
 12   user: name={{ mon_user }} state=present home=/opt/users/{{ mon_user }} group={{ mon_user_gid }} uid={{ mon_user_uid }} shell=/bin/bash password={{ db_password }} update_password=on_create
```

It's all good until I run:

ansible-playbook site.yaml -i hosts --check   --limit vsrv1942.int.belbone.be -vvvvv

which throws:

``` python
...
<vsrv1942.int.belbone.be> ESTABLISH CONNECTION FOR USER: root
ok: [vsrv1942.int.belbone.be] => {
    "mon_user_gid": "9000"
}
 ___________________________________________ 
< TASK: base_linux | ensure mon user exists >
 ------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


<vsrv1942.int.belbone.be> ESTABLISH CONNECTION FOR USER: root
<vsrv1942.int.belbone.be> REMOTE_MODULE user name=icinga state=present home=/opt/users/icinga group=9000 uid=9000 shell=/bin/bash password=VALUE_HIDDEN update_password=on_create CHECKMODE=True
<vsrv1942.int.belbone.be> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rik/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 vsrv1942.int.belbone.be /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008 && echo $HOME/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008'
<vsrv1942.int.belbone.be> PUT /tmp/tmp6MNJEA TO /root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user
<vsrv1942.int.belbone.be> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rik/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 vsrv1942.int.belbone.be /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user'
failed: [vsrv1942.int.belbone.be] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 3157, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 1532, in main
    (rc, out, err) = user.modify_user()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 600, in modify_user
    return self.modify_user_usermod()
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 384, in modify_user_usermod
    ginfo = self.group_info(self.group)
  File "/root/.ansible/tmp/ansible-tmp-1418388968.93-203439658602008/user", line 463, in group_info
    return list(grp.getgrgid(group))
TypeError: group id must be integer
OpenSSH_6.7p1, OpenSSL 1.0.1j 15 Oct 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 28037
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
Shared connection to vsrv1942.int.belbone.be closed.
```

If I change core/system/user.py group_info():

``` python
 459     def group_info(self,group):
 460         if not self.group_exists(group):
 461             return False
 462         if group.isdigit():
 463             return list(grp.getgrgid(group))
 464         else:
 465             return list(grp.getgrnam(group))
```

line 463

``` python
 459     def group_info(self,group):
 460         if not self.group_exists(group):
 461             return False
 462         if group.isdigit():
 463             return list(grp.getgrgid(int(group)))
 464         else:
 465             return list(grp.getgrnam(group))
```

Note -> list(grp.getgrgid(int(group)))
Where group HAS to be int since it passed isdigit()

Now if I rerun I get what I need:

``` python
< TASK: base_linux | ensure mon user exists >
 ------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


<vsrv1942.int.belbone.be> ESTABLISH CONNECTION FOR USER: root
<vsrv1942.int.belbone.be> REMOTE_MODULE user name=icinga state=present home=/opt/users/icinga group=9000 uid=9000 shell=/bin/bash password=VALUE_HIDDEN update_password=on_create CHECKMODE=True
<vsrv1942.int.belbone.be> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rik/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 vsrv1942.int.belbone.be /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418392144.95-256059181456859 && echo $HOME/.ansible/tmp/ansible-tmp-1418392144.95-256059181456859'
<vsrv1942.int.belbone.be> PUT /tmp/tmp_N9T_Y TO /root/.ansible/tmp/ansible-tmp-1418392144.95-256059181456859/user
<vsrv1942.int.belbone.be> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rik/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 vsrv1942.int.belbone.be /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1418392144.95-256059181456859/user'
ok: [vsrv1942.int.belbone.be] => {"append": false, "changed": false, "comment": "", "group": 9000, "home": "/opt/users/icinga", "move_home": false, "name": "icinga", "password": "NOT_LOGGING_PASSWORD", "shell": "/bin/bash", "state": "present", "uid": 9000}
 __________________________________________________ 
```

Thanks for your support, great soft, fun to use, easy to debug

**Comment by abadger** [comment]
Thanks for all the information!

Note that most modules have been moved to separate repositories so that more people could have commit rights.  The user module has moved to https://github.com/ansible/ansible-modules-core  so in the future you'll want to submit bug reports there.

With your information this was a quick fix, though, so I think I've pushed a change to fix this (see above).

thanks for reporting!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by pdelared** [comment]
Same thing on ansible 1.7.2, running on a RHEL box

changed line 455 on /usr/share/ansible/system/user

from:

```
return list(grp.getgrgid(group))
```

to 

```
 return list(grp.getgrgid(int(group)))
```

And worked for me on a RHEL 6.6 client
