### ISSUE TITLE
The pip module should support the --pypi-url argument to install

### ISSUE THREAD

**Issue by dlc** [ansible/ansible#982]
Our production environment does not have external internal access, so we maintain an internal pypi mirror. When installing packages with `pip`, we use the `--pypi-url=` option to install. It would be nice if the `pip` module took  a `pypiurl=` argument.

**Comment by mpdehaan** [comment]
I don't maintain the pip module, we are somewhat of an autonomous collective, so leaving this ticket open won't probably result in you getting what you want in the timetable you are expecting.  However, it's pretty easy to submit a pull request... 

Please submit a patch, making this an optional argument, and I'll take it.
