### ISSUE TITLE
if path given to vars_files is a directory load all *.yml files in it

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#984]
Allows conf.d like behavior from vars_files on the server

**Comment by mpdehaan** [comment]
this seems useful but also is unrequested by anyone, so let's not do this until that's the case.  I can't really think of a good use case.

**Comment by cweagans** [comment]
I requested this on IRC. My use case is this:

I want to have a directory where users can create yml files for each site that they're going to host on the system. When they run the Ansible playbook, Ansible should iterate over each yml file in this directory and create nginx configuration files for each site based on the data in the yml file.

**Comment by mpdehaan** [comment]
For most people this would be solved by #983 if you are just talking about pushing everything in a config.d folder using copy or template.

This was more about having a directory of variable files on the server side and being able to auto-merge them into the main variable dictionary.
