### ISSUE TITLE
apt with given package file fails in "--check" mode

### ISSUE THREAD

**Issue by tpo** [ansible/ansible#9844]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:

Debian/Debian
##### Summary:

ansible-playbook --check fails with "apt" module when given a Debian package file
##### Steps To Reproduce:

I have the following two tasks. The first copies the deb file over. The seconds installs the file:

```
- name: copy package.deb
  copy: src=package.deb dest=/tmp/
- name: install package.deb
  apt: deb=/tmp/package.deb
```

Evidently the package will not be copied over to the destination and thus it will also be missing there when it should be installed.
##### Expected Results:

The command/declaration should execute without failure. 
##### Actual Results:

 Running the tasks will result in the following when running ansible-playbook:

```
    TASK: [pkginstall | install package.deb] ***************************************
fatal: [target] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418844629.25-111234292060365/apt", line 1907, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418844629.25-111234292060365/apt", line 523, in main
    force=force_yes, dpkg_options=p['dpkg_options'])
  File "/root/.ansible/tmp/ansible-tmp-1418844629.25-111234292060365/apt", line 299, in install_deb
    pkg = apt.debfile.DebPackage(deb_file)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 57, in __init__
    self.open(filename)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 66, in open
    self._debfile = apt_inst.DebFile(self.filename)
SystemError: E:Could not open file /var/cache/apt/archives/package.deb - open (2: No such file or directory), E:Unable to determine the file size - fstat (9: Bad file descriptor), E:Read error - read (9: Bad file descriptor)

FATAL: all hosts have already failed -- aborting
```

**Comment by ibotty** [comment]
my expected result is what happens. if the package is not there, i expect the apt module to fail (because it would in practice as well).

you might be able to work around by using `always_run: yes` when copying the file or use `failed_when` in your `apt` task with some magic conditional that fails only when the file is present _and_ `apt` failed.

**Comment by tpo** [comment]
> my expected result is what happens. if the package is not there, i expect the apt module to fail (because it would in practice as well).
> 
> you might be able to work around by using always_run: yes when copying the file or use failed_when in your apt task with some magic conditional that fails only when the file is present and apt failed.

After a bit of deliberation I have to concur with you. Since you've improved the apt module to now fail gracefully, I think this issue can be closed, which I'm herewith doing. Please reopen if my closing of this issue doesn't fit with your workflow. Anyway, many thanks for the improvement and the suggestion lbotty.
