### ISSUE TITLE
Unable to revoke privileges for MySQL user

### ISSUE THREAD

**Issue by F21** [ansible/ansible#9848]
##### Issue Type:

Bug report
##### Ansible Version:

Ansible: ansible 1.8.2 configured module search path = None
##### Environment:

Environment: Ubuntu Server 14.10 64-bit running in virtualbox.
##### Summary:

The default mysql install comes with 2 privileges to allow anonymous users to access the `test` and `test_` databases.

I would like to remove all privileges for anonymous users. Unfortunately, using the `mysql_user` module fails with an error.
##### Steps To Reproduce:

Run this task:

``` yaml
- name: Revoke privileges for anonymous users
  mysql_user: 
    name: ''
    password: ''
    host: '{{ item }}'
    priv: '*.*:USAGE'
    state: present
    login_user: root
    login_password: '{{ mysql_root_password }}'
  with_items: [ '{{ ansible_hostname }}', 'localhost' ]
```
##### Expected Results:

Privileges should be revoked. No errors should be thrown.
##### Actual Results:

Unfortunately it does not revoke the privileges and throws an error:

```
==> default: TASK: [mysql | Revoke privileges for anonymous users] *************************
==> default: failed: [localhost] => (item=vagrant-ubuntu-utopic-64) => {"failed": true, "item": "vagrant-ubuntu-utopic-64"}
==> default: msg: unable to parse the MySQL grant string: GRANT USAGE ON *.* TO ''@'vagrant-ubuntu-utopic-64'
==> default: failed: [localhost] => (item=localhost) => {"failed": true, "item": "localhost"}
==> default: msg: unable to parse the MySQL grant string: GRANT USAGE ON *.* TO ''@'localhost'
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/root/playbook.retry
==> default:
```

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
