### ISSUE TITLE
DigitalOcean key generation

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#9854]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

Mac OS X
##### Summary:

If an SSH key exists in digitalocean, trying to "state=present" the same SSH public key with another name fails
##### Steps To Reproduce:
- Create an SSH key on the WebUI, and name it key1
- run this ansible task:

```
local_action: digital_ocean_sshkey state=present name=key2 ssh_pub_key={{digitalocean_ssh_key_file}} client_id={{digitalocean_client_id}} api_key={{digitalocean_api_key}}
```
##### Expected Results:

One of:
- An explanatory error message
- the key being renamed
- the id of the already existing key being returned (possibly with the name key1)
##### Actual Results:

```
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true}
msg: SSH Key failed to be created
```

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
