### ISSUE TITLE
default filter does not resolve variables in Ansible 1.8.2

### ISSUE THREAD

**Issue by jiwong** [ansible/ansible#9867]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

RHEL 5
##### Summary:

The default filter does not resolve variables defined in the inventory.  

For example, if I have defined in my inventory file the following variable:

app_install_dir=/test

My playbook has this and "somevariable" is not defined:

dest_dir="{{ somevariable | default('{{app_install_dir}}/DATA') }}"

When running the playbook, the default fails to resolve "app_install_dir"

This used to work on Ansible 1.7.1.
##### Steps To Reproduce:

1) Define a variable in the inventory called called "test_directory=/tmp/testdir"
2) In the playbook, have a task to create a directory defined by variable dest={{ undefined_variable | default('{{test_directory}}') }}
3) After running the playbook, it fails to resolve the value of "test_directory"
##### Expected Results:

The default filter should be able to resolve variables
##### Actual Results:

The default filter is not resolving variables defined in inventory

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

```
dest={{ undefined_variable | default('{{test_directory}}') }}
```

is an invalid expression , you cannot nest {{ }}, what you probably want is the following:

```
dest={{ undefined_variable | default(test_directory) }}
```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by glatapoui** [comment]
@bcoca: Good to know, but does that mean we cannot concatenate a variable and a literal in a default ? Something like: `dest={{ undefined_variable | default('{{test_directory}}/subdir') }}` (but not invalid ;-)

**Comment by bcoca** [comment]
I don't normally see posts in closed tickets but an irc user pinged me on this:
```dest={{ undefined_variable | default(test_directory + '/subdir') }} ```

**Comment by yuskul** [comment]
@bcoca 
Nice to see such a kind support of Ansible! Though the ticket is closed, but the described issue persists in Ansible 2.4.2. When I use an arg `vpc_subnet_id: "{{ vpc.subnets.id | default(item.subnet) }}"` in `ec2` module, it throws me a fail:

> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefin variable. The error was: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has  attribute 'subnets'\n\nThe error appears to have been in '/home/ec2-user/test/dashats-test.yml': line 39, column 5, but may\nbe elsewhere in the file depending on thexact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Start thenstances\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVarile'>\nexception: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribe 'subnets'"}


 But if I pass the (undefined) var with a one value (not nested in another value, as above), `vpc_subnet_id: "{{ vpc.subnets_id | default(item.subnet) }}"`. it runs well:

> TASK [Start the instances] ********************************************************
> ok: [localhost] => (item={u'subnet': u'subnet-43f0ee0a', u'group': [u'SSH'], u'ec2_ype': u't2.micro', u'tags': {u'type': u'ELB', u'Name': u'instance-01'}})


 Correct me, if I'm wrong.
