### ISSUE TITLE
Bug Report core module:user fails to generate ssh key in default location

### ISSUE THREAD

**Issue by OnlyLoveOleg** [ansible/ansible#9873]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9 (devel a55c6625d4) last updated 2014/12/21 17:35:19 (GMT +100)
  lib/ansible/modules/core: (detached HEAD dfe7f6c6d6) last updated 2014/12/21 17:41:58 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2014/12/21 17:42:06 (GMT +100)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/12/21 17:42:14 (GMT +100)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/12/21 17:42:22 (GMT +100)
  configured module search path = /usr/share/ansible
##### Environment:

Ansible node:
Ubuntu 14.04 x86_64

Managed:
Ubuntu 14.04 x86_64
##### Summary:

When managing users using the core user module I've tried to set the generate_ssh_key option to yes for already existing user on the managed node and got the following error.
##### Steps To Reproduce:
- Create a simple new user on the managed node using the user module.
- In the following playbook execution set the generate_ssh_key parameter to yes without specifying explicitly the ssh_key_file parameter.
##### Expected Results:

Pair of keys generated in user's home directory.
##### Actual Results:

failed: [managed_node] => (item={'generate_ssh_key': True, 'name': 'user1', 'authorized': [{'key': ''}]}) => {"failed": true, "item": {"authorized": [{"key": ""}], "generate_ssh_key": true, "name": "user1"}, "name": "user1", "rc": 1}
msg: Failed to create /home/user1/$HOME/.ssh: [Errno 2] No such file or directory: '/home/user1/$HOME/.ssh'

FATAL: all hosts have already failed -- aborting

NOTE: Setting the parameter  ssh_key_file explicitly works fine (for example /home/user1/.ssh/id_rsa)

**Comment by encbladexp** [comment]
Keep in Mind to enable createhome=yes, anyway a pending Pull Request to create SSH Keys only after creating $HOME is here: https://github.com/ansible/ansible-modules-core/pull/544

Currently Ansible tries to create SSH Keys before creating an $HOME (at least for existing Users).

**Comment by OnlyLoveOleg** [comment]
:) Thanks for the fast resolution, createhome is yes by default and the home dir was on the managed node before the second play.

**Comment by OnlyLoveOleg** [comment]
@encbladexp thanks for the fix but moving the block in user.py not fixing the issue described. I've applied your fix manually and the same issue persist even when on remote you have the full path /home/$user/.ssh

**Comment by encbladexp** [comment]
Maybe different Problems…

**Comment by abadger** [comment]
From the output, the problem is that the user module is putting both  "/home/user1/" and "$HOME" into the ssh key file path.  However, I've been unable to replicate this on ubuntu14.04.  Could you supply a playbook that does the two calls to user that you describe?  Maybe I'll be able to reproduce your problem with that.

**Comment by OnlyLoveOleg** [comment]
Sure thing, I wrote a simple role to manage users on the system using the core modules user and authorized_key:

Can be found here:
https://github.com/pjili/ansible/tree/master/roles/Users

The tasks portion of the role:

```
---
- name: Debian | Manage users
  user: >
   append={{ item.append |default(omit)}}
   comment={{ item.comment |default(omit)}}
   createhome={{ item.createhome |default(omit)}}
   force={{ item.force |default(omit)}}
   generate_ssh_key={{ item.generate_ssh_key |default(omit)}}
   group={{ item.group |default(omit)}}
   groups={{ item.groups |default(omit)}}
   home={{ item.home |default(omit)}}
   login_class={{ item.login_class |default(omit)}}
   move_home={{ item.move_home |default(omit)}}
   name={{ item.name |mandatory}}
   non_unique={{ item.non_unique |default(omit)}}
   password={{ item.password |default(omit)}}
   remove={{ item.remove |default(omit)}}
   shell={{ item.shell |default(omit)}}
   ssh_key_bits={{ item.ssh_key_bits |default("2048")}}
   ssh_key_comment={{ item.ssh_key_comment |default("ansible-generated")}}
   ssh_key_file={{ item.ssh_key_file |default("$HOME/.ssh/id_rsa")}}
   ssh_key_passphrase={{ item.ssh_key_passphrase |default(omit)}}
   ssh_key_type={{ item.ssh_key_type |default("rsa")}}
   state={{ item.state |default("present")}}
   system={{ item.system |default(omit)}}
   uid={{ item.uid |default(omit)}}
   update_password={{ item.update_password |default("always")}}
  with_items: users
  when: users is defined

- name: Debian | Manage SSH authorized keys
  authorized_key: >
   key='{{ item.1.key }}'
   key_options='{{ item.1.key_options | default(omit) }}'
   manage_dir='{{ item.1.manage_dir | default("yes") }}'
   path='{{ item.1.path | default(omit) }}'
   state='{{ item.1.state | default("present") }}'
   user={{ item.0.name }}
  with_subelements:
   - users
   - authorized
```

For the initial run just to create the user I've used the following variable in group_vars:

```
users:
     - name: user1
       authorized:
        - key: ''
```

Next I've tried to generate the keys and changed the variable to:

```
users:
     - name: user1
       generate_ssh_key: yes
       authorized:
        - key: ''
```

Maybe I'am doing something wrong here?

**Comment by abadger** [comment]
Thanks, reproduced with that.  Looking into what could be happening now.

**Comment by abadger** [comment]
The problem looks to be this line from your role:

``` python
     ssh_key_file={{ item.ssh_key_file |default("$HOME/.ssh/id_rsa")}}
```

Ansible isn't a shell and so $HOME isn't being processed.  Looking at the user module documentation I can see how that mistake could be made as it says that "$HOME/.ssh/id_rsa" is the default.

The user module currently expands any relative directories to be rooted in the user's home directory.  So what you probably want to specify is 

``` python
     ssh_key_file={{ item.ssh_key_file |default(".ssh/id_rsa")}}
```

I'll update the documentation to mention this directory handling behaviour.

**Comment by OnlyLoveOleg** [comment]
Thanks a lot for the fix! Told you it's probably me doing something silly :)
