### ISSUE TITLE
lineinfile 'create=yes' with '--check' fails with SELinux

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#9874]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2 (also tried on latest dev)
##### Environment:

Centos 6.6
##### Summary:

`lineinfile` module when using `creates=yes` with `--check` fails on a machine which is running SELinux (with SELinux set to permissive) if a file doesn't exist already. I know `lineinfile` is a now in ansible-modules-core, but this is not a bug with the module, but with the core, specifically with the file `ansible/lib/ansible/module_utils/basic.py`.
##### Steps To Reproduce:

SELinux needs to be enabled (in my case it is set to permissive):

```
# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /selinux
Current mode:                   permissive
Mode from config file:          disabled
Policy version:                 24
Policy from config file:        targeted
```

And here is the test playbook to reproduce this problem:

```

---
- hosts: localhost
  gather_facts: no
  tasks:
    - lineinfile: dest=/tmp/something_that_doesnt_exist create=yes regexp='^1000' line='test'
```
##### Expected Results:

The playbook should report that task as changed.
##### Actual Results:

The task fails:

```
ansible-playbook test.yml -C

PLAY [localhost] *********************************************************

TASK: [lineinfile dest=/tmp/something_that_doesnt_exist create=yes regexp='^1000' line='test'] ***
failed: [localhost] => {"failed": true, "path": "/tmp/something_that_doesnt_exist", "state": "absent"}
msg: path /tmp/something_that_doesnt_exist does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/user/test.retry

localhost             : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!

**Comment by kustodian** [comment]
This is not a bug in the module, but in the core.

**Comment by abadger** [comment]
It seems you've already done some debugging on this -- have you figured out where in basic.py this is happening?

**Comment by kustodian** [comment]
This is now fixed in the current devel branch, so all is good. And it was an error in the module, I didn't investigate enough at that time to find what was the problem, since the ansible core was throwing an error and not the module, but the problem was that the module didn't call core functions correctly.
