### ISSUE TITLE
git module: overwrites local commits

### ISSUE THREAD

**Issue by phryneas** [ansible/ansible#9898]
Hi, this is relatively easy to reproduce:

```
git clone your-repo
cd your-repo
touch asd
git add asd
git commit -a -m 'asd'
```

Now start an ansible playbook to pull "your-repo" to the same destination.

Expected result: a merge, or at least a warning

Result: all local commits are deleted

This is definitely not intended as without the commit, and with "force=no", there is a warning. With the commit and "force=no" all files are overwritten without warning.

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
