### ISSUE TITLE
0.8 - template, assemble, and lineinfile should have backup= like copy 

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#990]
The `copy` module has a `backup=` option (#828) which ought to be made available to `template`, `assemble`, `lineinfile` modules for consistency.

**Comment by mpdehaan** [comment]
Basically it just needs to be handled by the copy client module to serve template -- we need to see why that is not working presently.   assemble would need a seperate implementation, which implies a function should be written for the module common code for that, ditto the lineinfile module.

**Comment by jpmens** [comment]
Thank you!
