### ISSUE TITLE
Feature Idea: Run syntax/file/role/etc checks before asking for passwords/user inupt

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible#9904]
For example, if I'm running a play than needs the --ask-sudo-pass flag, then ansible should not ask for the password until after it's checked for syntax errors, that all the roles exist, and other pre-task checks.

**Comment by lielran** [comment]
:+1:

**Comment by baldurmen** [comment]
This is a very good idea. It's _very_ frustrating to have to type a long password to then have ansible tell you the playbook cannot be found since your path was wrong.
