### ISSUE TITLE
Bug Report: EC2: instance ID does not exist

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#9918]
Issue Type: Bug Report

Ansible Version: 1.8.2

Environment: Ubuntu 14.04

Summary:

This appears to be similar to #7906 

When provisioning several instances in a loop via the EC2 module, instance tagging will frequently fail with:

`msg: Instance tagging failed => InvalidInstanceID.NotFound: The instance ID 'i-xxxxxx' does not exist`

I find it to happen much more frequently when >5 instances are being provisioned in a with_items loop.

Example task:

```
name: Provision new instances
      ec2:
        count: 1
        image: "{{ ec2_image }}"
        instance_type: "{{ ec2_instance_type }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        keypair: "{{ ec2_keypair }}"
        volumes: "{{ ec2_volumes }}"
        instance_tags:
          Name: "{{ item }}"
        region: "{{ ec2_region }}"
        group_id: "{{ ec2_sg_id }}"
        vpc_subnet_id: "{{ ec2_subnet_id }}"
        wait: no
      with_items: new_hosts
```

Example output:

```
TASK: [Provision new instances] ***********************************************
changed: [localhost] => (item=(0, u'host-23.internal.com'))
changed: [localhost] => (item=(1, u'host-24.internal.com'))
changed: [localhost] => (item=(2, u'host-25.internal.com'))
changed: [localhost] => (item=(3, u'host-26.internal.com'))
changed: [localhost] => (item=(4, u'host-27.internal.com'))
failed: [localhost] => (item=(5, u'host-28.internal.com')) => {"failed": true, "item": [5, "host-28.internal.com"]}
msg: Instance tagging failed => InvalidInstanceID.NotFound: The instance ID 'i-xxxxxxx' does not exist
failed: [localhost] => (item=(6, u'host-29.internal.com')) => {"failed": true, "item": [6, "host-29.internal.com"]}
msg: Instance tagging failed => InvalidInstanceID.NotFound: The instance ID 'i-yyyyyyy' does not exist
changed: [localhost] => (item=(7, u'host-30.internal.com'))

FATAL: all hosts have already failed -- aborting
```

This appears to be a race condition between provisioning and tagging--if many instances are being provisioned, the instance will not be ready for tagging and the playbook fails.

Steps To Reproduce:

Attempt to provision >5 EC2 instances with instance_tags. Do so serially via with_items loop.

Expected Results:

Successful provisioning.

Actual Results:

One or more instances fail to be tagged and the playbook fails.

Workaround:

Use `wait: yes` on the EC2 task.

**Comment by mpdehaan** [comment]
Hi!

As part of our recent module restructing, modules have been moved to two different repos.   

These are:

https://github.com/ansible/ansible-modules-core
https://github.com/ansible/ansible-modules-extras

Whether a module is in core or extras can be found by consulting the documentation page for the module, where this will be noted at the bottom of the documentation page.

If you can please reopen this ticket on one of the two trackers above, we would appreciate it.

Thank you very much!
