### ISSUE TITLE
SSH connections sometimes hang

### ISSUE THREAD

**Issue by Nirkus** [ansible/ansible#9920]
Hey,

I just started with ansible and put 2 remote machines in my /etc/ansible/hosts.
Sometimes, one or both SSH connections just hang when issuing `ansible all -m ping -u remoteuser`
Most of the times, it just works. Starting ansible with `-vvvv` does not provide any debug output when those connection hangs occur, but I can see the problematic connections sendq increase/not decrease with `netstat -np`.
So, this seems to be an issue with:
a) my local Linux TCP stack on IPv6
b) the ControlMaster conn handling of my local OpenSSH revision
c) the ControlMaster conn handling of my local ansible revision

My guess is a combination of c) and b) as I did not encounter any other SSH conections and could not find anything similiar with a quick Google search.

Any pointers on how to debug this issue?
Local workstation environmet with ansible issues:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.0 (jessie)
Release:    8.0
Codename:   jessie

$ uname -a
Linux osmium 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux

$ getconf LONG_BIT
64

$ ansible --version
ansible 1.7.2

$ python -V
Python 2.7.8

$ ssh -V
OpenSSH_6.7p1 Debian-3, OpenSSL 1.0.1j 15 Oct 2014

$ netstat -np --inet --inet6
[..]
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
[..]
tcp6       0   4036 2001:... 2a01:... ESTABLISHED 8141/ansible-ssh-ne
[..]
tcp6       0   1820 2001:... 2a01:... ESTABLISHED 8132/ansible-ssh-ar

```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by Nirkus** [comment]
FYI
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778825
