### ISSUE TITLE
Bug Report: etcd_url setting is not respected

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#9921]
Issue Type: Bug Report

Ansible Version: 1.8.2

Environment: Ubuntu 14.04 / OS X Yosemite

Summary:

The etcd lookup has a configurable host setting for connecting to etcd nodes that are not localhost. There are two ways to accomplish this:
- "etcd_url" setting in ansible.cfg
- ANSIBLE_ETCD_URL environment variable

Only the second (environment variable) seems to have any effect. 

Steps To Reproduce:
1. Create an external etcd cluster with nodes on different machines than those from which you will be running Ansible.
2. Create a playbook that pulls one or more variables from etcd via lookup. Example (playbook/roles/my_role/vars/main.yml): `my_var: "{{ lookup('etcd', 'foo/bar/baz') }}"`
3. Put the following setting in the defaults section of the playbook's ansible.cfg: `etcd_url = 'http://etcd-node-1.mydomain.net:4001'`
4. Run playbook.

Expected Results:

"my_var" is defined with value from etcd.

Actual Results:

"my_var" is an empty string.

Workaround:

Use ANSIBLE_ETCD_URL environmental variable with every playbook run.

**Comment by bcoca** [comment]
This was purposefully removed in 643690ffec0cde15f13f131c102aad498661fea7 and 5b3c796641bb6a19780d7eb5db5d52e578c780d0.
