### ISSUE TITLE
ansible-playbook should support running without / with an empty inventory file.

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#9932]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

N/A
##### Summary:

ansible-playbook should not signal an error when no inventory file is specified. Should treat it as empty (and perhaps output a warning) instead.

This is a valid use-case for local playbooks where all plays are delegated to 127.0.1 with connection: local.
##### Steps To Reproduce:

Create a playbook:

```
- hosts: 127.0.0.1
  connection: local
  tasks:
    - command: pwd
```

run it with `ansible-playbook test.yml -v`
##### Expected Results:

The playbook should run and output the current working directory.
##### Actual Results:

`ERROR: Unable to find an inventory file, specify one with -i ?`

**Comment by axos88** [comment]
Currently the inventory file should exist, and should not be empty, but other than that it can contain anything, it can be even gibberish.

**Comment by hfinucane** [comment]
My usual pattern for this is

```
ansible-playbook -i localhost, test.yml
```

**Comment by bcoca** [comment]
#9913 makes empty inventory a warning now
