### ISSUE TITLE
Ansible modifies PYTHONPATH which causes Python commands to fail

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#9956]
**Issue Type:**

Bug

**Ansible Version:**

1.8.2

**Environment:**

OS X Yosemite / Homebrew

**Summary:**

Ansible appears to modify PYTHONPATH internally to vendored versions of some modules. This causes Python scripts executed within playbooks to potentially fail if there are module conflicts.

Test playbook tasks:

```
    - name: Getting PYTHONPATH
      local_action: shell python3 -c 'import sys; print(":".join(sys.path))'
      register: pythonpath

    - debug:
        msg: "PYTHONPATH: {{ pythonpath.stdout }}"
```

Output:

```
TASK: [Getting PYTHONPATH] ****************************************************
changed: [localhost -> 127.0.0.1]

TASK: [debug ] ****************************************************************
ok: [localhost] => {
    "msg": "PYTHONPATH: :/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages:/usr/local/Cellar/ansible/1.8.2/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python34.zip:/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4:/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin:/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload:/usr/local/lib/python3.4/site-packages"
}
```

Note the first two entries: 
- /usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages
- /usr/local/Cellar/ansible/1.8.2/libexec/vendor/lib/python2.7/site-packages

These entries alter the Python execution environment within playbooks and can cause scripts to fail.

I see this error trying to execute a Python 3 script from within an ansible playbook, failing on a PyYAML module conflict:

Affected playbook tasks:

```
    - name: Run Python 3 script
      local_action: "shell python3 ../../utils/scripts/example_script.py"
      register: py3_test
```

Output:

```
TASK: [Get new host info] *****************************************************
failed: [localhost -> 127.0.0.1] => {"changed": true, "cmd": "python3 ../../utils/scripts/example_script.py", "delta": "0:00:00.043137", "end": "2015-01-07 17:04:02.318020", "rc": 1, "start": "2015-01-07 17:04:02.274883", "warnings": []}
stderr: Traceback (most recent call last):
  File "../../utils/scripts/example_script.py", line 9, in <module>
    from shared import dsc_shared
  File "/Users/bkeroack/code/infrastructure-automation/utils/scripts/shared/__init__.py", line 4, in <module>
    import yaml
  File "/usr/local/Cellar/ansible/1.8.2/libexec/vendor/lib/python2.7/site-packages/yaml/__init__.py", line 2, in <module>
    from error import *
ImportError: No module named 'error'

FATAL: all hosts have already failed -- aborting
```

The same script runs normally when run from a bash shell (ie, not within an Ansible playbook).

**Steps To Reproduce:**
1. Create a Python 3 script that references a module that is vendored within the Ansible installation.
2. Attempt to execute this script within a playbook.

**Expected Results:**

Script runs normally.

**Actual Results:**

Within Ansible, script dies with module ImportError.

**Comment by cchurch** [comment]
Looks like a homebrew packaging issue, not an ansible issue?

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ansible.rb

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- Ansible does not change the python path, the installation method should put ansible modules and libraries within the existing path, in this case it looks like you used homebrew which we do not maintain. 

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by abadger** [comment]
Some additional information:

```
$ ansible-playbook env.yml                              *[devel]  (09:31:45)

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [shell python3 -c "import sys ; print(sys.path)"] *********************** 
changed: [localhost -> 127.0.0.1]

TASK: [debug ] **************************************************************** 
ok: [localhost] => {
    "msg": "PYTHONPATH: ['', '/usr/lib64/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/home/badger/.local/lib/python3.4/site-packages', '/usr/lib64/python3.4/site-packages', '/usr/lib/python3.4/site-packages']"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=1    unreachable=0    failed=0 
```

This output shows that upstream ansible code isn't modifying PYTHONPATH.  So this isn't something that we can solve upstream.  It has to do with the way that homebrew has packaged ansible for consumption and would need to be fixed in the homebrew packaging.

**Comment by bkeroackdsc** [comment]
Thank you. I've opened a Homebrew issue: https://github.com/Homebrew/homebrew/issues/35647

**Comment by InferGuard** [comment]
Hello,

The bug or the confusion between python different path is stil existing in el captant,
any idea or workaround ?
am trying to not work with a something like a  ln -s /usr/bin/python /usr/local/bin/python2.7
