### ISSUE TITLE
1.8 vars_files cannot use a templated path anymore (worked in 1.7)

### ISSUE THREAD

**Issue by BrandonMathis** [ansible/ansible#9962]
Upgraded to 1.8.3 and I am getting a lot of `error while evaluating conditional` errors. What can I do to help you guys assist me in diagnosing this problem?

**Comment by bcoca** [comment]
we need a bit more to go on, OS would be nice, a small play to reproduce the error, etc

**Comment by BrandonMathis** [comment]
Well. I am developing a tool called [tape](https://github.com/smashingboxes/tape) which uses ansible to deploy servers.

The developer installs this tool and can set custom vars in a `site_vars.yml` file that is put in the root of his application's repo.

I was able to make ansible use this custom vars file by setting a `local_dir` variable in my vars/defaults.yml [like this](https://github.com/smashingboxes/tape/blob/0.2.1/omnibox.yml#L7)

It worked fine for a while but 1.8.3 broke this

I changed the way the custom vars file is loaded to [this](https://github.com/smashingboxes/tape/blob/0.2.2/omnibox.yml) and everything is good now.

I wish someone could explain to me why ansible 1.8.3 is treating vars files differently from 1.7

**Comment by bcoca** [comment]
I'm assuming you mean 1.8.2 as 1.8.3 would involve a tardis and possibly parallel universes.

1.8 fixed many issues with variable loading and templating, which created some issues, specially with previously undefined (but sometimes used) behavior.

changing title accordingly.

**Comment by jgornick** [comment]
#10009

**Comment by bcoca** [comment]
folding into #9723 as dupe
