### ISSUE TITLE
SSH host key changed

### ISSUE THREAD

**Issue by axos88** [ansible/ansible#9964]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
  configured module search path = None
##### Environment:

Mac OS X
##### Summary:

If a host identification changed (in regards with ~/.ssh/known_hosts) ansible swallows the warning, and nothing is output (not even at -vvvv).
This results in SSH denying to forward agent for no apparent reason, even if it is set up in ansible.cfg

[ssh_connection]
ssh_args= -o ForwardAgent=yes
##### Steps To Reproduce:
- Change host identification for one of your hosts in ~/.ssh/known_hosts.
- Set up ansible.cfg to forward agent
- Observe agent forwarding to fail when connecting to the host
##### Expected Results:

A warning about identification mismatch
##### Actual Results:

Silent ignore

**Comment by jctanner** [comment]
ssh related errors have been significantly revamped in 2.2 to expose all stdout and stderr to the user as to avoid situations like this. Please check your testcase with one of the recent 2.2 release candidates or 2.2 final once it is out.

needs_info

**Comment by axos88** [comment]
Not using ansible anymore, can't confirm or deny.

**Comment by mkwardakov** [comment]
Prerequisites:
```
$ ansible --version
ansible 2.2.0.0
  config file = /home/michael/.ansible.cfg
  configured module search path = Default w/o overrides
$ cat inventory
[elk]
srv5-runville.net
$ cat ~/.ansible.cfg
[defaults]
host_key_checking = True
ssh_args=-o ForwardAgent=yes
```
First run:
```
$ ansible -i inventory elk -m ping --user=user
srv5-runville.net | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```
After host ket changed:
```
ssh user@srv5-una.net
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:GKC8Fk7y7eP399UuIVJ2IJZHY1T/uZXGWHW9xojSzKM.
Please contact your system administrator.
Add correct host key in /home/michael/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/michael/.ssh/known_hosts:59
  remove with:
  ssh-keygen -f "/home/michael/.ssh/known_hosts" -R srv5-una.net
ECDSA host key for srv5-una.net has changed and you have requested strict checking.
Host key verification failed.
```
ansible ignores:
```
$ ansible -i inventory elk -m ping --user=user
srv5-runville.net | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```
Tried with
```
$ cat ~/.ansible.cfg
[defaults]
host_key_checking = False
#ssh_args=-o ForwardAgent=yes
```
same result, false positive.

**Comment by bcoca** [comment]
So the error does appear, but can be 'obscured' when using control master as the connection is persistent and the key is not 're checked'.  I'm closing this issue as this is a known behaviour of ssh.
