### ISSUE TITLE
Variables aren't evaluated in the module command/shell

### ISSUE THREAD

**Issue by adyscr** [ansible/ansible#9965]
Hello,
Here is a part of code that it's not working 
Ansible version 1.8.2

``` ---
- hosts: karma
  user: root
  sudo: True
  tasks:
    - shell: cp /images/KBU*.tar /images/KBU/
    - shell: cd /images/KBU/ && tar -xvf KBU*.tar
    - shell: MODULE_GOROCO="$(ls /images/KBU/ | grep KBUONE | awk -F- '{print $4}' | awk -F. '{print $1}' | tail -1)"; echo "${MODULE_GOROCO}"
    - shell: echo "path to rpms /images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/"
    - shell: cd $(echo "/images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/")
```

the command: 

```
    - shell: MODULE_GOROCO="$(ls /images/KBU/ | grep KBUONE | awk -F- '{print $4}' | awk -F. '{print $1}' | tail -1)"; echo "${MODULE_GOROCO}"
```

works, it resolves the variable, it echos the corrct value, but 

```
cd $(echo "/images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/")
```

 this error appears: 

```
/bin/sh: line 0: cd: /images/KBU/PA-KBU-KBUONE-/rpms/jboss/: No such file or directory
```

What am I doing wrong ? The ${MODULE_GOROCO is the version of the app being deployed and I need it every time since it depends on the name from the .tar and that value needs to be exported.

How can I use the "environment:" module when the value I am getting from the remote host stripping some paths and getting the version on app?

**Comment by adyscr** [comment]
Also I'm seeing a problem when running the playbook like this: 

```
ansible-playbook -vvvv /etc/ansible/play
```

for every shell:... that is executed, ansible is connecting to the machine and executing the command, it does not remain connected to the machine and runs a hole playbook.

```
TASK: [shell export MODULE_GOROCO="$(ls /images/KBU/ | grep KBUONE | awk -F- '{print $4}' | awk -F. '{print $1}' | tail -1)"; echo "${MODULE_GOROCO}"; echo "path to rpms /images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/"; cd $(echo "/images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/"); pwd] ***
<10.192.234.38> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.192.234.38
<10.192.234.38> REMOTE_MODULE command export MODULE_GOROCO="$(ls /images/KBU/ | grep KBUONE | awk -F- '{print $4}' | awk -F. '{print $1}' | tail -1)"; echo "${MODULE_GOROCO}"; echo "path to rpms /images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/"; cd $(echo "/images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/"); pwd #USE_SHELL
<10.192.234.38> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1420811875.55-163370730166462 && echo $HOME/.ansible/tmp/ansible-tmp-1420811875.55-163370730166462'
<10.192.234.38> PUT /tmp/tmpGC93Xr TO /root/.ansible/tmp/ansible-tmp-1420811875.55-163370730166462/command
```

it gives me the output desired:

```
G10R00C00
path to rpms /images/KBU/PA-KBU-KBUONE-G10R00C00/rpms/jboss/
/images/KBU/PA-KBU-KBUONE-G10R00C00/rpms/jboss
```

but if i put a shell: pwd - to run after the above task:

```
TASK: [shell pwd] *************************************************************
<10.192.234.38> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.192.234.38
<10.192.234.38> REMOTE_MODULE command pwd #USE_SHELL
<10.192.234.38> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1420811882.34-135826380802572 && echo $HOME/.ansible/tmp/ansible-tmp-1420811882.34-135826380802572'
<10.192.234.38> PUT /tmp/tmpfmaPZH TO /root/.ansible/tmp/ansible-tmp-1420811882.34-135826380802572/command
```

and it gives:

```
stdout:
/root
```

Not good at all !

**Comment by sivel** [comment]
I think there is a little bit of misunderstanding here.

Each task shell task is run separate and independent of any previous shell task.  As such, setting an env var in a previous task, will not make it available for a later task.

So these 2 tasks won't work as you expect:

```
    - shell: MODULE_GOROCO="$(ls /images/KBU/ | grep KBUONE | awk -F- '{print $4}' | awk -F. '{print $1}' | tail -1)"; echo "${MODULE_GOROCO}"
    - shell: echo "path to rpms /images/KBU/PA-KBU-KBUONE-${MODULE_GOROCO}/rpms/jboss/"
```

You set `MODULE_GOROCO` in 1 task, and then try to access it in the next.  At the next task, a new shell and connection is used, so that env var no longer exists.

You would need to either set that in all tasks before you use it, or use the 'environment' option on a task to provide it to the task.

**Comment by bcoca** [comment]
as @sivel mentions above, each task uses it's own shell, the connection itself might be reused (i.e. ssh + persistance) but the shell environment is new for every task.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

We would suggest:
- make this a script and execute it with the script module
- or use registered vars to pass the values down from one task to the rest

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
