### ISSUE TITLE
setup module should check socket class to see whether it's ipv6 capable (again)

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#997]
From suggestion from @sfromm, it looks like this has regressed a bit given new default network interface facts and other changes.

We should look at the socket class and then don't try ipv6 data if not there.

Test with ipv6 disabled and see that everything is ok.

**Comment by sfromm** [comment]
Feel free to assign to me and I'll take a look at re-injecting it.

**Comment by mpdehaan** [comment]
Ok, if you can't get to it by tomorrow just let me know, I'm thinking fixing this prior to release is desirable.

Thanks very much!

**Comment by mpdehaan** [comment]
I pushed a small change in  eed031c ... if you think more is required, feel free to send me a fix.

I'm going to shoot for releasing 0.7 sometime after 6pm EST tomorrow

**Comment by sfromm** [comment]
On Wed, Sep 5, 2012 at 5:22 PM, Michael DeHaan notifications@github.comwrote:

> I pushed a small change in eed031chttps://github.com/ansible/ansible/commit/eed031c... if you think more is required, feel free to send me a fix.
> 
> I'm going to shoot for releasing 0.7 sometime after 6pm EST tomorrow
> 
> I think your change covers it.

sf
