### ISSUE TITLE
Install using pip doesn't seem to work after v1.7.2

### ISSUE THREAD

**Issue by skipthelimit** [ansible/ansible#9987]
I used to be able to install the latest version like this:

```
pip install -Iv https://github.com/ansible/ansible/archive/v1.7.2.zip
```

Or like this:

```
pip install -Iv https://github.com/ansible/ansible/archive/devel.zip
```

But now, all the versions after 1.7.2 give me this error when using ansible:

```
ERROR: apt is not a legal parameter in an Ansible task or handler
```

**Comment by bcoca** [comment]
The github archives were never a supported manner of installation, this cannot work now that ansible is spread across 3 different repos.  This link documents how to install ansible in a supported fashion:

http://docs.ansible.com/intro_installation.html
